In [93]:
import pandas as pd
import numpy as np

In [94]:
pd.set_option('display.max_rows' , None)
pd.set_option('display.max_columns' , None)

In [95]:
df = pd.read_csv('flats - flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
866,4 BHK Flat in Sector 103 Gurgaon,https://www.99acres.com/4-bhk-bedroom-apartmen...,Indiabulls Centrum Park3.7 ★,2.14 Crore,"₹ 7,443/sq.ft.",Super Built up area 2875(267.1 sq.m.)Carpet ar...,4 Bedrooms,6 Bathrooms,3+ Balconies,Servant Room,"G3-74, Sector 103 Gurgaon, Gurgaon, Haryana",7th of 18 Floors,East,1 to 5 Year Old,"['Gurgaon Dreamz Mall', 'HUDA Market, Sector 1...",Indiabulls centrum park is one of the most pop...,"['1 Exhaust Fan', '10 Light', 'No AC', 'No Bed...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area5 out of 5', 'Construction4 out of...",Y68884816
1756,3 BHK Flat in Sector 79 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Mapsko Mount Ville4.1 ★,1.2 Crore,"₹ 8,053/sq.ft.",Super Built up area 1490(138.43 sq.m.),3 Bedrooms,3 Bathrooms,3 Balconies,NaN,"123, Sector 79 Gurgaon, Gurgaon, Haryana",24th of 30 Floors,West,1 to 5 Year Old,"['Huda Metro Station (Gurugram)', 'Sapphire 83...",3 bhk. 3 bath near to nh 8 waking distance onl...,"['3 Wardrobe', '5 Fan', '1 Exhaust Fan', '3 Ge...","['Lift(s)', 'Park']","['Green Area5 out of 5', 'Construction5 out of...",J69571808
2567,2 BHK Flat in Sector 81 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Signature Global City 81,89 Lac,"₹ 8,279/sq.ft.",Carpet area: 1075 (99.87 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Others,"Sector 81 Gurgaon, Gurgaon, Haryana",3rd of 4 Floors,North,Oct-24,"['Ambience Mall New', 'Dwarka Expressway', 'NH...","Payment in quaterly installments , to pays app...","['2 Wardrobe', '4 Fan', '2 Geyser', '4 Light',...","['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Environment4.5 out of 5', 'Lifestyle4 out of...",M68963232
448,3 BHK Flat in Sector 67 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,M3M Merlin3.7 ★,3.5 Crore,"₹ 14,583/sq.ft.",Super Built up area 2400(222.97 sq.m.)Carpet a...,3 Bedrooms,4 Bathrooms,3 Balconies,"Servant Room,Store Room","1701, Sector 67 Gurgaon, Gurgaon, Haryana",17th of 25 Floors,South-East,1 to 5 Year Old,"['Airia Mall', 'Golf Course Extension Road', '...",This 3 bhk apartment is available for sale in ...,"['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '4 Ge...","['Centrally Air Conditioned', 'Water purifier'...","['Green Area4 out of 5', 'Construction4 out of...",H69409856
846,3 BHK Flat in Sector 71 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,CHD Avenue 713.6 ★,1.1 Crore,"₹ 6,104/sq.ft.",Super Built up area 1802(167.41 sq.m.),3 Bedrooms,4 Bathrooms,3 Balconies,Servant Room,"Sector 71 Gurgaon, Gurgaon, Haryana",3rd of 14 Floors,South,5 to 10 Year Old,"['Huda City Centre', 'Apna Mart', 'Rajiv Chowk...",Best price in this location near by reputed sc...,NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...","['Green Area5 out of 5', 'Construction3 out of...",N69335420

In [96]:
df.shape

(3007, 20)

In [97]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3007 entries, 0 to 3006
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3007 non-null   object
 1   link             3007 non-null   object
 2   society          3006 non-null   object
 3   price            3007 non-null   object
 4   area             2996 non-null   object
 5   areaWithType     3007 non-null   object
 6   bedRoom          3007 non-null   object
 7   bathroom         3007 non-null   object
 8   balcony          3007 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3001 non-null   object
 11  floorNum         3005 non-null   object
 12  facing           2126 non-null   object
 13  agePossession    3006 non-null   object
 14  nearbyLocations  2912 non-null   object
 15  description      3007 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2593 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3007 non-null   object
dtypes: object(20)
memory usage: 470.0+ KB

In [98]:
df.duplicated().sum()

0

In [99]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                 0
area                 11
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1313
address               6
floorNum              2
facing              881
agePossession         1
nearbyLocations      95
description           0
furnishDetails      804
features            414
rating              331
property_id           0
dtype: int64

In [100]:
df.drop(columns = ['link' , 'property_id'],inplace=True)

In [101]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [102]:
df.rename(columns = {'area' : 'price_per_sqft'} , inplace = True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [103]:
df['society'].value_counts

<bound method IndexOpsMixin.value_counts of 0                                  maa bhagwati residency
1                                            Apna Enclave
2                                  Tulsiani Easy in Homes
3                                     Smart World Orchard
4                                        Parkwood Westend
5                          Signature Global Infinity Mall
6                                              The Cocoon
7                                        ATS Triumph3.9 ★
8                                       Vatika Xpressions
9                                          Raheja Revanta
10                               Signature Global City 81
11                                 HCBS Sports Ville3.6 ★
12                                     Supertech Araville
13                                                 Godrej
14                              Shree Vardhman Flora3.8 ★
15                                             Sobha City
16                                           Senate Court
17              Shapoorji Pallonji Joyville Gurugram4.0 ★
18                             Central Park Flower Valley
19                                       Smart World Gems
20                                         Bestech Altura
21                                       Smart World Gems
22                            Emaar Imperial Gardens3.8 ★
23                                La Vida by Tata Housing
24                              The New People Apartments
25                                            The Serenas
26                                    M3M Golfestate4.4 ★
27               Central Park Resort Belgravia Residences
28                                          Apex builders
29                                         Godrej Habitat
30                                    Ompee K S Residency
31                                            Bhawna CGHS
32                                    Adani Aangan Arcade
33                                        Sare Green Parc
34                              Shree Vardhman Flora3.8 ★
35                                         Supertech Hues
36                                 Chintels Paradiso3.9 ★
37                                 Breez Global Hill View
38                                        ILD Greens4.1 ★
39                                   Ansal Sushant Lok CI
40                                       Ashiana Mulberry
41                                        Godrej Meridien
42                                 Mapsko Casa Bella3.8 ★
43                                        Pooja Apartment
44                             Signature Global Park4.0 ★
45                            DLF New Town Heights 13.9 ★
46                                             Paras Dews
47                                             Godrej Air
48                                    DLF The Primus3.9 ★
49                  Emaar MGF Emerald Floors Premier3.8 ★
50                                DLF Regency Park 13.6 ★
51                                     Supertech Araville
52                             Signature Global Park4.0 ★
53                               Maxworth City Residences
54                                           Deepak Minda
55                                  Shree Shyam residency
56                                         Pivotal Devaan
57                            Unitech The Residences3.7 ★
58                                     CHD Avenue 713.6 ★
59                         Gokuldham Society, Bahadurgarh
60                                 Silverglades The Melia
61                Sare Crescent Parc Royal Greens Phase 1
62                                Umang Winter Hills3.9 ★
63                                        Ramprastha Skyz
64                                       4S Aradhya Homes
65                                        ILD Greens4.1 ★
66                            BPTP Freedom Park Life4.0 ★
67                                         Godrej Habitat
68                                   Ramsons Kshitij3.7 ★
69                                      Sidhartha NCR One
70                                         Raheja Sampada
71                                  Signature The Serenas
72                          Pareena Laxmi Apartments3.6 ★
73                               Satya The Hermitage3.5 ★
74                                       Smart World Gems
75                                 GLS Arawali Homes3.8 ★
76                             Signature Global Park4.0 ★
77                          Bestech Park View City 23.9 ★
78                              Shree Vardhman Flora3.8 ★
79                               AFNHB Jalvayu Vihar3.7 ★
80                                          M3M Soulitude
81                                          Pyramid Elite
82                                Emaar MGF Palm Terraces
83                                        Anamika Enclave
84                                 HCBS Sports Ville3.6 ★
85                                     Puri The Aravallis
86                            Brisk Lumbini Terrace Homes
87                          HUDA Ashok Vihar Phase 13.9 ★
88                                                My Home
89                                  Signature Global City
90                                            M3M Heights
91                             Signature Global Park4.0 ★
92                             Signature Global Park4.0 ★
93                                     Godrej Nature Plus
94                                         Supertech Hues
95                            DLF New Town Heights 13.9 ★
96           Central Park Flower Valley Aqua Front Towers
97                                     Ambience Creacions
98                              Signature Global City 63A
99                                      Godrej Oasis3.9 ★
100                                           M3M Skycity
101                                    Supertech Araville
102                                   Smart World Orchard
103                                HCBS Sports Ville3.6 ★
104                                    Emaar Palm Premier
105                                    Godrej Nature Plus
106                                      Godrej Aria3.8 ★
107                                  Ramsons Kshitij3.7 ★
108                                         Conscient One
109                         Pareena Laxmi Apartments3.6 ★
110                                         Pyramid Elite
111                                        Raheja Revanta
112                                           M3M Skycity
113                            Signature The Roselia3.6 ★
114                                        Not Applicable
115                                    Godrej Nature Plus
116                                       Ramprastha City
117                                       Smartworld 1DXP
118                           Ansal Housing Highland Park
119                                 Czar Mahira Homes 63A
120                             Breez Global Heights4.2 ★
121                                   Trisara Our Homes 3
122                                         M3M Soulitude
123                             Emaar MGF Palm Hills4.0 ★
124                                       Ramprastha City
125                              Pareena Coban Residences
126                               La Vida by Tata Housing
127                               La Vida by Tata Housing
128                           Godrej Summit Premia Towers
129                                       Ardee City3.8 ★
130                                 M3M One Key Resiments
131                                      Ansal Heights 86
132                                       MVN Athens3.7 ★
133                                 Signature The Serenas
134                          Sushant Lok 1 Builder Floors
135                                  Umang Monsoon Breeze
136                                         GLS Avenue 51
137                          Signature Global Solera3.7 ★
138                                    Supertech Araville
139                                           Greenopolis
140          Central Park Flower Valley Aqua Front Towers
141                                            Sare Homes
142             Vatika Sovereign Next Sector-82 A Gurgaon
143                                        Bhagwati sadan
144                                      Smart World Gems
145                                         micasa sec 68
146                                  Eldeco Accolade3.8 ★
147                                            Hero Homes
148                                           Shyam Sadan
149                                           M3M Heights
150                                   hanumanta apartment
151                                    Supertech Hilltown
152                                            ashiyara 2
153                                  Raheja Vedaanta3.6 ★
154                                       BPTP Terra3.8 ★
155                                      Green Court3.7 ★
156                                M3M Golf Hills Phase 1
157                         Abhinav Group Housing Society
158                                 Pyramid Urban Homes 2
159                                           M3M Heights
160                                    Godrej Nature Plus
161                                   Smart World Orchard
162                                    Ashiana Anmol3.5 ★
163                                  Signature Signum 95A
164                               Umang Winter Hills3.9 ★
165                                        Aardhya homesh
166                                            ROF Ananda
167                                      Smart World Gems
168                                        Assotech Blith
169                                           Essel Tower
170                                          Raheja Vanya
171                                    Vatika INXT Floors
172                                   Palam Vihar Society
173                                     Godrej Oasis3.9 ★
174                             DLF New Town Heights3.7 ★
175                             DLF New Town Heights3.7 ★
176         sonata group housing society sector 1 Manesar
177                                        Supertech Hues
178                                Krrish Florence Estate
179                         Piedmont Taksila heights3.6 ★
180                                    Experion Heartsong
181                                      SS The Leaf3.8 ★
182                                            M3M Urbana
183                                   AIPL Zen Residences
184                                DLF Regal Gardens3.9 ★
185                                            Godrej Air
186                                 Suncity Vatsal Valley
187                                 Shree shyam residency
188                                Project Krishna Colony
189                                       MVN Athens3.7 ★
190                                     M3M Antalya Hills
191                            Central Park Flower Valley
192                                           M3M Capital
193                                    Ansal Heights3.2 ★
194                                          Malibu Towne
195                                   AIPL Zen Residences
196                                           M3M Heights
197                                HCBS Sports Ville3.6 ★
198                                HCBS Sports Ville3.6 ★
199                                            JMD Empire
200                             Housing Apna Enclave3.7 ★
201                                        Assotech Blith
202                                       Pareena Mi Casa
203                                  Suncity Heights3.7 ★
204                                       Lotus Homz4.0 ★
205                        Ramson kshitij Sec-95 Gurugram
206                                   Maruti Vihar Colony
207                                           M3M Heights
208                                      Supertech Basera
209                        Signature Global the Millennia
210                                         M3M Soulitude
211                                          Raheja Vanya
212            Ganpati apartment  2, Laxman Vihar Phase 1
213                            Ramprastha The Atrium3.4 ★
214                                        M3M Golfestate
215                                  Eldeco Accolade3.8 ★
216                                           M3M Heights
217                                           M3M Heights
218                                 Vatika Sovereign Next
219                                           M3M Heights
220                                           M3M Heights
221                                           M3M Heights
222                                   South City 1 Floors
223                                          Allure Homes
224                                           Zara Aavaas
225                        Sidhartha NCR One Phase 14.2 ★
226                                    CHD Avenue 713.6 ★
227                       Ramprastha The Edge Towers3.5 ★
228                                    Supertech Araville
229                                     Imperia Aashiyara
230                               La Vida by Tata Housing
231             Shapoorji Pallonji Joyville Gurugram4.0 ★
232                                   Smart World Orchard
233                                    Supertech Araville
234                                   Smart World Orchard
235                           Unitech The Residences3.7 ★
236                           Emaar Imperial Gardens3.8 ★
237                                            Sare Homes
238                                           Greenopolis
239                                        Pivotal Devaan
240                                       Today Callidora
241                M M Residency, Krishna Colony, Gurgaon
242                               Signature Global Park 4
243                                    CHD Avenue 713.6 ★
244                                  Park Royal Apartment
245               Vatika Boulevard Residences and Heights
246                        Signature Global the Millennia
247                                           M3M Heights
248             Shapoorji Pallonji Joyville Gurugram4.0 ★
249                                        Tulip Monsella
250                         Shyamkunj ashok vihar pahse 2
251                                    Godrej Nature Plus
252                                           M3M Heights
253                                   M3M The Marina4.0 ★
254                                       Emaar Digihomes
255                                  Umang Monsoon Breeze
256                                  Mapsko Paradise3.9 ★
257                                        Cancon Enclave
258                                    Tata Primanti4.1 ★
259                                     MRG World Ultimus
260                            sonata group housing Gh 24
261                                         BPTP Pedestal
262                                   Smart World Orchard
263                                  HSIIDC Sidco Aravali
264                                      Godrej Aria3.8 ★
265                                        Assotech Blith
266                               Sare Crescent Parc3.5 ★
267                                        Unitech Vistas
268                                    Supertech Araville
269                           Ansal Housing Highland Park
270                                      Tulip White3.5 ★
271                                Mapsko Casa Bella3.8 ★
272                       Unitech Uniworld Gardens 23.4 ★
273                                             ILD Grand
274                                           M3M Capital
275                                        Unitech Vistas
276                       Ramprastha The Edge Towers3.5 ★
277                                      Smart World Gems
278                                 Sapphire Eighty Three
279                              Pareena Coban Residences
280                               Sare Crescent Parc3.5 ★
281                                         DLF The Grove
282                                     Baani City Center
283                                     Indiabulls Enigma
284                                      SS The Leaf3.8 ★
285                                   Smart World One DXP
286                                  Sukhshanti Apartment
287                                   M3M Golfestate4.4 ★
288                      Bestech Park View Residency3.9 ★
289                                            SS Almeria
290                                      JMD Gardens4.4 ★
291                                  CGHS Agrim Apartment
292                                      Global Hill View
293                              Ireo Victory Valley4.1 ★
294                                       Emaar Digihomes
295                                    Godrej Nature Plus
296                               DLF Carlton Estate4.0 ★
297                                   Smart World Orchard
298                            Signature Global Park4.0 ★
299                          Railway Officers RPF Society
300                                            Godrej Air
301                             Emaar MGF Palm Hills4.0 ★
302                                          Maruti Vihar
303                                    Vasant Appartments
304                                      Ansal Heights 86
305             Shapoorji Pallonji Joyville Gurugram4.0 ★
306                                    Puri The Aravallis
307                                  The Close North4.0 ★
308                                   Smart World Orchard
309                             Emaar Gurgaon Greens4.1 ★
310                                    Godrej Nature Plus
311                                Landmark The Residency
312                                           M3M Capital
313                           Emaar Imperial Gardens3.8 ★
314                             DLF Belvedere Towers3.8 ★
315                                             m3m crown
316                                       Godrej 1014.0 ★
317                             Central Park Resorts4.4 ★
318                                  Sukhshanti Apartment
319                                   M3M Golfestate4.4 ★
320                      Bestech Park View Residency3.9 ★
321                                            SS Almeria
322                              Ireo Victory Valley4.1 ★
323                                       Emaar Digihomes
324                               DLF Carlton Estate4.0 ★
325                            Signature Global Park4.0 ★
326                          Railway Officers RPF Society
327                                            Godrej Air
328                             Emaar MGF Palm Hills4.0 ★
329                                          Maruti Vihar
330                                    Vasant Appartments
331                                      Ansal Heights 86
332             Shapoorji Pallonji Joyville Gurugram4.0 ★
333                                  The Close North4.0 ★
334                             Emaar Gurgaon Greens4.1 ★
335                                Landmark The Residency
336                           Emaar Imperial Gardens3.8 ★
337                             DLF Belvedere Towers3.8 ★
338                                       Godrej 1014.0 ★
339                                        Tulip Monsella
340               Sare Crescent Parc Royal Greens Phase 1
341                                  AIPL Club Residences
342                           Experion The Heartsong3.9 ★
343                                 Signature Global City

In [104]:
df['society'].value_counts().shape

(635,)

In [105]:
import re
df['society'] = df['society'].apply(lambda name: re.sub(r'\d+(\.\d+)?\s?★' , '',str(name)).strip()).str.lower()

In [106]:
df['society'].value_counts

<bound method IndexOpsMixin.value_counts of 0                              maa bhagwati residency
1                                        apna enclave
2                              tulsiani easy in homes
3                                 smart world orchard
4                                    parkwood westend
5                      signature global infinity mall
6                                          the cocoon
7                                         ats triumph
8                                   vatika xpressions
9                                      raheja revanta
10                           signature global city 81
11                                  hcbs sports ville
12                                 supertech araville
13                                             godrej
14                               shree vardhman flora
15                                         sobha city
16                                       senate court
17               shapoorji pallonji joyville gurugram
18                         central park flower valley
19                                   smart world gems
20                                     bestech altura
21                                   smart world gems
22                             emaar imperial gardens
23                            la vida by tata housing
24                          the new people apartments
25                                        the serenas
26                                     m3m golfestate
27           central park resort belgravia residences
28                                      apex builders
29                                     godrej habitat
30                                ompee k s residency
31                                        bhawna cghs
32                                adani aangan arcade
33                                    sare green parc
34                               shree vardhman flora
35                                     supertech hues
36                                  chintels paradiso
37                             breez global hill view
38                                         ild greens
39                               ansal sushant lok ci
40                                   ashiana mulberry
41                                    godrej meridien
42                                  mapsko casa bella
43                                    pooja apartment
44                              signature global park
45                               dlf new town heights
46                                         paras dews
47                                         godrej air
48                                     dlf the primus
49                   emaar mgf emerald floors premier
50                                   dlf regency park
51                                 supertech araville
52                              signature global park
53                           maxworth city residences
54                                       deepak minda
55                              shree shyam residency
56                                     pivotal devaan
57                             unitech the residences
58                                         chd avenue
59                     gokuldham society, bahadurgarh
60                             silverglades the melia
61            sare crescent parc royal greens phase 1
62                                 umang winter hills
63                                    ramprastha skyz
64                                   4s aradhya homes
65                                         ild greens
66                             bptp freedom park life
67                                     godrej habitat
68                                    ramsons kshitij
69                                  sidhartha ncr one
70                                     raheja sampada
71                              signature the serenas
72                           pareena laxmi apartments
73                                satya the hermitage
74                                   smart world gems
75                                  gls arawali homes
76                              signature global park
77                             bestech park view city
78                               shree vardhman flora
79                                afnhb jalvayu vihar
80                                      m3m soulitude
81                                      pyramid elite
82                            emaar mgf palm terraces
83                                    anamika enclave
84                                  hcbs sports ville
85                                 puri the aravallis
86                        brisk lumbini terrace homes
87                             huda ashok vihar phase
88                                            my home
89                              signature global city
90                                        m3m heights
91                              signature global park
92                              signature global park
93                                 godrej nature plus
94                                     supertech hues
95                               dlf new town heights
96       central park flower valley aqua front towers
97                                 ambience creacions
98                          signature global city 63a
99                                       godrej oasis
100                                       m3m skycity
101                                supertech araville
102                               smart world orchard
103                                 hcbs sports ville
104                                emaar palm premier
105                                godrej nature plus
106                                       godrej aria
107                                   ramsons kshitij
108                                     conscient one
109                          pareena laxmi apartments
110                                     pyramid elite
111                                    raheja revanta
112                                       m3m skycity
113                             signature the roselia
114                                    not applicable
115                                godrej nature plus
116                                   ramprastha city
117                                   smartworld 1dxp
118                       ansal housing highland park
119                             czar mahira homes 63a
120                              breez global heights
121                               trisara our homes 3
122                                     m3m soulitude
123                              emaar mgf palm hills
124                                   ramprastha city
125                          pareena coban residences
126                           la vida by tata housing
127                           la vida by tata housing
128                       godrej summit premia towers
129                                        ardee city
130                             m3m one key resiments
131                                  ansal heights 86
132                                        mvn athens
133                             signature the serenas
134                      sushant lok 1 builder floors
135                              umang monsoon breeze
136                                     gls avenue 51
137                           signature global solera
138                                supertech araville
139                                       greenopolis
140      central park flower valley aqua front towers
141                                        sare homes
142         vatika sovereign next sector-82 a gurgaon
143                                    bhagwati sadan
144                                  smart world gems
145                                     micasa sec 68
146                                   eldeco accolade
147                                        hero homes
148                                       shyam sadan
149                                       m3m heights
150                               hanumanta apartment
151                                supertech hilltown
152                                        ashiyara 2
153                                   raheja vedaanta
154                                        bptp terra
155                                       green court
156                            m3m golf hills phase 1
157                     abhinav group housing society
158                             pyramid urban homes 2
159                                       m3m heights
160                                godrej nature plus
161                               smart world orchard
162                                     ashiana anmol
163                              signature signum 95a
164                                umang winter hills
165                                    aardhya homesh
166                                        rof ananda
167                                  smart world gems
168                                    assotech blith
169                                       essel tower
170                                      raheja vanya
171                                vatika inxt floors
172                               palam vihar society
173                                      godrej oasis
174                              dlf new town heights
175                              dlf new town heights
176     sonata group housing society sector 1 manesar
177                                    supertech hues
178                            krrish florence estate
179                          piedmont taksila heights
180                                experion heartsong
181                                       ss the leaf
182                                        m3m urbana
183                               aipl zen residences
184                                 dlf regal gardens
185                                        godrej air
186                             suncity vatsal valley
187                             shree shyam residency
188                            project krishna colony
189                                        mvn athens
190                                 m3m antalya hills
191                        central park flower valley
192                                       m3m capital
193                                     ansal heights
194                                      malibu towne
195                               aipl zen residences
196                                       m3m heights
197                                 hcbs sports ville
198                                 hcbs sports ville
199                                        jmd empire
200                              housing apna enclave
201                                    assotech blith
202                                   pareena mi casa
203                                   suncity heights
204                                        lotus homz
205                    ramson kshitij sec-95 gurugram
206                               maruti vihar colony
207                                       m3m heights
208                                  supertech basera
209                    signature global the millennia
210                                     m3m soulitude
211                                      raheja vanya
212        ganpati apartment  2, laxman vihar phase 1
213                             ramprastha the atrium
214                                    m3m golfestate
215                                   eldeco accolade
216                                       m3m heights
217                                       m3m heights
218                             vatika sovereign next
219                                       m3m heights
220                                       m3m heights
221                                       m3m heights
222                               south city 1 floors
223                                      allure homes
224                                       zara aavaas
225                           sidhartha ncr one phase
226                                        chd avenue
227                        ramprastha the edge towers
228                                supertech araville
229                                 imperia aashiyara
230                           la vida by tata housing
231              shapoorji pallonji joyville gurugram
232                               smart world orchard
233                                supertech araville
234                               smart world orchard
235                            unitech the residences
236                            emaar imperial gardens
237                                        sare homes
238                                       greenopolis
239                                    pivotal devaan
240                                   today callidora
241            m m residency, krishna colony, gurgaon
242                           signature global park 4
243                                        chd avenue
244                              park royal apartment
245           vatika boulevard residences and heights
246                    signature global the millennia
247                                       m3m heights
248              shapoorji pallonji joyville gurugram
249                                    tulip monsella
250                     shyamkunj ashok vihar pahse 2
251                                godrej nature plus
252                                       m3m heights
253                                    m3m the marina
254                                   emaar digihomes
255                              umang monsoon breeze
256                                   mapsko paradise
257                                    cancon enclave
258                                     tata primanti
259                                 mrg world ultimus
260                        sonata group housing gh 24
261                                     bptp pedestal
262                               smart world orchard
263                              hsiidc sidco aravali
264                                       godrej aria
265                                    assotech blith
266                                sare crescent parc
267                                    unitech vistas
268                                supertech araville
269                       ansal housing highland park
270                                       tulip white
271                                 mapsko casa bella
272                          unitech uniworld gardens
273                                         ild grand
274                                       m3m capital
275                                    unitech vistas
276                        ramprastha the edge towers
277                                  smart world gems
278                             sapphire eighty three
279                          pareena coban residences
280                                sare crescent parc
281                                     dlf the grove
282                                 baani city center
283                                 indiabulls enigma
284                                       ss the leaf
285                               smart world one dxp
286                              sukhshanti apartment
287                                    m3m golfestate
288                       bestech park view residency
289                                        ss almeria
290                                       jmd gardens
291                              cghs agrim apartment
292                                  global hill view
293                               ireo victory valley
294                                   emaar digihomes
295                                godrej nature plus
296                                dlf carlton estate
297                               smart world orchard
298                             signature global park
299                      railway officers rpf society
300                                        godrej air
301                              emaar mgf palm hills
302                                      maruti vihar
303                                vasant appartments
304                                  ansal heights 86
305              shapoorji pallonji joyville gurugram
306                                puri the aravallis
307                                   the close north
308                               smart world orchard
309                              emaar gurgaon greens
310                                godrej nature plus
311                            landmark the residency
312                                       m3m capital
313                            emaar imperial gardens
314                              dlf belvedere towers
315                                         m3m crown
316                                            godrej
317                              central park resorts
318                              sukhshanti apartment
319                                    m3m golfestate
320                       bestech park view residency
321                                        ss almeria
322                               ireo victory valley
323                                   emaar digihomes
324                                dlf carlton estate
325                             signature global park
326                      railway officers rpf society
327                                        godrej air
328                              emaar mgf palm hills
329                                      maruti vihar
330                                vasant appartments
331                                  ansal heights 86
332              shapoorji pallonji joyville gurugram
333                                   the close north
334                              emaar gurgaon greens
335                            landmark the residency
336                            emaar imperial gardens
337                              dlf belvedere towers
338                                            godrej
339                                    tulip monsella
340           sare crescent parc royal greens phase 1
341                              aipl club residences
342                            experion the heartsong
343                             signature global city
344                            bestech park view city
345                                emaar palm gardens
346                                        chd avenue
347                                        mvn athens
348                                 mahindra luminare
349                                   raheja navodaya
350                                godrej nature plus
351                                        m3m urbana
352                            experion the heartsong
353                                        sobha city
354                                godrej nature plus
355                               smart world orchard
356                          emaar mgf the palm drive
357                       bestech park view residency
358                       bestech park view residency
359                                        m3m merlin
360                                  dlf the skycourt
361                              emaar gurgaon greens
362                               afnhb jalvayu vihar
363                                  dlf regency park
364                               ireo victory valley
365                                ambience creacions
366                          signature global city 92
367      the khushboo cooperative housing society ltd
368                           adani m2k oyster grande

In [107]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [108]:
df['price'].value_counts

<bound method IndexOpsMixin.value_counts of 0                 45 Lac
1                 50 Lac
2                 40 Lac
3             1.47 Crore
4                 70 Lac
5                 41 Lac
6                2 Crore
7              1.8 Crore
8              1.1 Crore
9             4.75 Crore
10                96 Lac
11                29 Lac
12            1.35 Crore
13                95 Lac
14                70 Lac
15            3.95 Crore
16                90 Lac
17            1.05 Crore
18             2.2 Crore
19            1.01 Crore
20            1.85 Crore
21                86 Lac
22            1.85 Crore
23            2.85 Crore
24      Price on Request
25                42 Lac
26            6.15 Crore
27            6.25 Crore
28                42 Lac
29            1.35 Crore
30             1.6 Crore
31            3.25 Crore
32                45 Lac
33                85 Lac
34                75 Lac
35                82 Lac
36             1.8 Crore
37             29.99 Lac
38                78 Lac
39               2 Crore
40                74 Lac
41             3.2 Crore
42             1.3 Crore
43                25 Lac
44                95 Lac
45            1.99 Crore
46            1.05 Crore
47            1.83 Crore
48            2.25 Crore
49             2.8 Crore
50             1.6 Crore
51                83 Lac
52                83 Lac
53                80 Lac
54            1.25 Crore
55                23 Lac
56                30 Lac
57            1.55 Crore
58                79 Lac
59                50 Lac
60            1.01 Crore
61                95 Lac
62                99 Lac
63             1.1 Crore
64             1.9 Crore
65               1 Crore
66             2.5 Crore
67             1.1 Crore
68                29 Lac
69                55 Lac
70                65 Lac
71                50 Lac
72             31.75 Lac
73                93 Lac
74             1.2 Crore
75                30 Lac
76                56 Lac
77             2.7 Crore
78               1 Crore
79            1.45 Crore
80            1.25 Crore
81                46 Lac
82             4.5 Crore
83                64 Lac
84                28 Lac
85            3.87 Crore
86            1.38 Crore
87                43 Lac
88              28.5 Lac
89             1.1 Crore
90               2 Crore
91                90 Lac
92                90 Lac
93            1.75 Crore
94                93 Lac
95             1.8 Crore
96             2.1 Crore
97               2 Crore
98               2 Crore
99            1.29 Crore
100           2.85 Crore
101            1.1 Crore
102           1.65 Crore
103               24 Lac
104            2.1 Crore
105            1.9 Crore
106            1.1 Crore
107             31.5 Lac
108            1.7 Crore
109               32 Lac
110               45 Lac
111            1.2 Crore
112            2.1 Crore
113               45 Lac
114               42 Lac
115           1.55 Crore
116            1.3 Crore
117           2.75 Crore
118           1.25 Crore
119               42 Lac
120               40 Lac
121               34 Lac
122           1.25 Crore
123            1.5 Crore
124            1.3 Crore
125            1.6 Crore
126            1.5 Crore
127            1.5 Crore
128               90 Lac
129            1.5 Crore
130               80 Lac
131           1.25 Crore
132               26 Lac
133               42 Lac
134            2.5 Crore
135               90 Lac
136               42 Lac
137               50 Lac
138               90 Lac
139            1.3 Crore
140            1.7 Crore
141           1.25 Crore
142           2.91 Crore
143           1.15 Crore
144            1.2 Crore
145            1.5 Crore
146            1.3 Crore
147           1.75 Crore
148               55 Lac
149            2.5 Crore
150               43 Lac
151               80 Lac
152               45 Lac
153               70 Lac
154           1.95 Crore
155               45 Lac
156            1.7 Crore
157            1.1 Crore
158               50 Lac
159            2.8 Crore
160           1.45 Crore
161            2.2 Crore
162               90 Lac
163               40 Lac
164           1.35 Crore
165           1.85 Crore
166               25 Lac
167               88 Lac
168           1.15 Crore
169            1.6 Crore
170               85 Lac
171               75 Lac
172           3.35 Crore
173            1.5 Crore
174           1.65 Crore
175              2 Crore
176           1.75 Crore
177               90 Lac
178           1.25 Crore
179              1 Crore
180           1.08 Crore
181           2.15 Crore
182              1 Crore
183           1.65 Crore
184           1.79 Crore
185            1.8 Crore
186           1.45 Crore
187               22 Lac
188               36 Lac
189               25 Lac
190           1.15 Crore
191           1.65 Crore
192            2.9 Crore
193               60 Lac
194            2.4 Crore
195           1.25 Crore
196           2.15 Crore
197             29.5 Lac
198               38 Lac
199            1.5 Crore
200               39 Lac
201            1.6 Crore
202            1.7 Crore
203           3.25 Crore
204               60 Lac
205               27 Lac
206               95 Lac
207           2.65 Crore
208               36 Lac
209               55 Lac
210           1.32 Crore
211               59 Lac
212               45 Lac
213               90 Lac
214            1.4 Crore
215               95 Lac
216              3 Crore
217           3.67 Crore
218           3.85 Crore
219           3.29 Crore
220           2.33 Crore
221           2.79 Crore
222            3.4 Crore
223               72 Lac
224               40 Lac
225               56 Lac
226            1.1 Crore
227               71 Lac
228               78 Lac
229               40 Lac
230           1.85 Crore
231            1.1 Crore
232           1.41 Crore
233           1.45 Crore
234            2.2 Crore
235            1.1 Crore
236           2.05 Crore
237               60 Lac
238               80 Lac
239               41 Lac
240               90 Lac
241               54 Lac
242               82 Lac
243              1 Crore
244           1.85 Crore
245           1.42 Crore
246               55 Lac
247           2.29 Crore
248               97 Lac
249           8.25 Crore
250               30 Lac
251           1.65 Crore
252           1.99 Crore
253              1 Crore
254           4.25 Crore
255           1.25 Crore
256               95 Lac
257           1.05 Crore
258            4.1 Crore
259               50 Lac
260           1.65 Crore
261            1.6 Crore
262            2.1 Crore
263               90 Lac
264            1.1 Crore
265               92 Lac
266               70 Lac
267               99 Lac
268             71.5 Lac
269             87.5 Lac
270               91 Lac
271           1.25 Crore
272           1.05 Crore
273               66 Lac
274           1.83 Crore
275            52.56 Lac
276               80 Lac
277           1.71 Crore
278               65 Lac
279            1.3 Crore
280               82 Lac
281            5.7 Crore
282               88 Lac
283              4 Crore
284           1.93 Crore
285           3.45 Crore
286            1.7 Crore
287           6.15 Crore
288            1.4 Crore
289           1.48 Crore
290           3.25 Crore
291           1.49 Crore
292               30 Lac
293           3.49 Crore
294           2.15 Crore
295            1.4 Crore
296              2 Crore
297            2.3 Crore
298               54 Lac
299           1.25 Crore
300           1.05 Crore
301           1.25 Crore
302              1 Crore
303            1.7 Crore
304            1.3 Crore
305           2.12 Crore
306            3.9 Crore
307              3 Crore
308            2.2 Crore
309           1.35 Crore
310           1.67 Crore
311               90 Lac
312           2.37 Crore
313           1.98 Crore
314            3.7 Crore
315           4.67 Crore
316           1.29 Crore
317           3.65 Crore
318            1.7 Crore
319           6.15 Crore
320            1.4 Crore
321           1.48 Crore
322           3.49 Crore
323           2.15 Crore
324              2 Crore
325               54 Lac
326           1.25 Crore
327           1.05 Crore
328           1.25 Crore
329              1 Crore
330            1.7 Crore
331            1.3 Crore
332           2.12 Crore
333              3 Crore
334           1.35 Crore
335               90 Lac
336           1.98 Crore
337            3.7 Crore
338           1.29 Crore
339            5.6 Crore
340           1.25 Crore
341           1.27 Crore
342           1.36 Crore
343              1 Crore
344           4.25 Crore
345            1.8 Crore
346           1.25 Crore
347               27 Lac
348            5.5 Crore
349               85 Lac
350           1.07 Crore
351               95 Lac
352               87 Lac
353            4.1 Crore
354           1.27 Crore
355           1.47 Crore
356           3.45 Crore
357           1.18 Crore
358           1.55 Crore
359           3.39 Crore
360           1.54 Crore
361           1.42 Crore
362            1.3 Crore
363           2.25 Crore
364            3.5 Crore
365            4.8 Crore
366               78 Lac
367               88 Lac
368            2.6 Crore
369            3.4 Crore
370            2.9 Crore
371               70 Lac
372            1.5 Crore
373           1.28 Crore
374           2.51 Crore
375            6.5 Crore
376           3.63 Crore
377           1.85 Crore
378           2.45 Crore
379           1.38 Crore
380            5.9 Crore
381              3 Crore
382           2.01 Crore
383            2.1 Crore
384           4.25 Crore
385           2.55 Crore
386              2 Crore
387           3.25 Crore
388            1.6 Crore
389            1.5 Crore
390           3.75 Crore
391               95 Lac
392            1.4 Crore
393           1.56 Crore
394           1.35 Crore
395            1.4 Crore
396           2.26 Crore
397            1.2 Crore
398           2.08 Crore
399           1.75 Crore
400           2.99 Crore
401            2.1 Crore
402           2.87 Crore
403           2.35 Crore
404              3 Crore
405              6 Crore
406           2.35 Crore
407            1.9 Crore
408               72 Lac
409               65 Lac
410           2.34 Crore
411           2.57 Crore
412           1.71 Crore
413           3.79 Crore
414           2.05 Crore
415            5.2 Crore
416            3.2 Crore
417               69 Lac
418           3.75 Crore
419           3.65 Crore
420           5.49 Crore
421           1.05 Crore
422           3.35 Crore
423            2.4 Crore
424           1.71 Crore
425            6.3 Crore
426            2.2 Crore
427           3.25 Crore
428          11.25 Crore
429            3.3 Crore
430           1.51 Crore
431           1.38 Crore
432            4.6 Crore
433            1.4 Crore
434            3.5 Crore
435               99 Lac
436           2.65 Crore
437            2.4 Crore
438           1.65 Crore
439           1.25 Crore
440              4 Crore
441            1.8 Crore
442           1.75 Crore
443           2.35 Crore
444           7.15 Crore
445           1.64 Crore
446            2.8 Crore
447           6.75 Crore
448            3.5 Crore
449            4.6 Crore
450           2.25 Crore
451            2.2 Crore
452           2.85 Crore
453           1.76 Crore
454              1 Crore
455            3.6 Crore
456           1.78 Crore
457               98 Lac
458           2.82 Crore
459           3.21 Crore
460            1.9 Crore
461           1.19 Crore
462           1.35 Crore
463            1.8 Crore
464           1.35 Crore
465            1.7 Crore
466            1.6 Crore
467           2.65 Crore
468            54.99 Lac
469            1.4 Crore
470           1.26 Crore
471            1.7 Crore
472            4.1 Crore
473           1.01 Crore
474           1.45 Crore
475            1.6 Crore
476           2.99 Crore
477            1.9 Crore
478           1.75 Crore
479            1.3 Crore
480           2.95 Crore
481            3.4 Crore
482           3.32 Crore
483               95 Lac
484           1.55 Crore
485           1.54 Crore
486           2.45 Crore
487            2.6 Crore
488           1.83 Crore
489           1.09 Crore
490           1.87 Crore
491           1.05 Crore
492           1.77 Crore
493            2.2 Crore
494               60 Lac
495            1.8 Crore
496               64 Lac
497               75 Lac
498           4.95 Crore
499           4.25 Crore
500           5.31 Crore
501            1.4 Crore
502            2.8 Crore
503            4.1 Crore
504            3.4 Crore
505           3.05 Crore
506           4.25 Crore
507           1.16 Crore
508           3.55 Crore
509            1.8 Crore
510           1.75 Crore
511            1.2 Crore
512           1.52 Crore
513           1.55 Crore
514            2.4 Crore
515           2.35 Crore
516           2.28 Crore
517            1.1 Crore
518            2.3 Crore
519           1.35 Crore
520           2.45 Crore
521               90 Lac
522            2.8 Crore
523            1.4 Crore
524           1.36 Crore
525             98.5 Lac
526             56.2 Lac
527            2.2 Crore
528            1.2 Crore
529           1.33 Crore
530               87 Lac
531           1.09 Crore
532              3 Crore
533           1.75 Crore
534           1.75 Crore
535            3.8 Crore
536            3.5 Crore
537           1.78 Crore
538           1.08 Crore
539           2.03 Crore
540           1.12 Crore
541              2 Crore
542           1.04 Crore
543           1.25 Crore
544           2.05 Crore
545           3.19 Crore
546           3.85 Crore
547            3.2 Crore
548             88.5 Lac
549               49 Lac
550           1.65 Crore
551           2.35 Crore
552            1.4 Crore
553               97 Lac
554           2.35 Crore
555           3.32 Crore
556           1.25 Crore
557            2.8 Crore
558            4.7 Crore
559            1.3 Crore
560               62 Lac
561               80 Lac
562           1.73 Crore
563           4.45 Crore
564            2.3 Crore
565            2.2 Crore
566           2.12 Crore
567           2.25 Crore
568            1.9 Crore
569            4.4 Crore
570           1.75 Crore
571            2.8 Crore
572           4.63 Crore
573           1.32 Crore
574           1.16 Crore
575               27 Lac
576            27.75 Lac
577           1.79 Crore
578           1.55 Crore
579           1.55 Crore
580           3.35 Crore
581            3.5 Crore
582            4.8 Crore
583            1.5 Crore
584           2.78 Crore
585           2.25 Crore
586           2.55 Crore
587           1.25 Crore
588               85 Lac
589           5.25 Crore
590            1.3 Crore
591               75 Lac
592           3.65 Crore
593           1.65 Crore
594           1.25 Crore
595           1.42 Crore
596           1.27 Crore
597           1.65 Crore
598           1.24 Crore
599            2.7 Crore
600           1.98 Crore
601            2.5 Crore
602           2.29 Crore
603           2.98 Crore
604           1.35 Crore
605           1.37 Crore
606           1.55 Crore
607           4.25 Crore
608           1.28 Crore
609           1.95 Crore
610           2.35 Crore
611              5 Crore
612               99 Lac
613           1.95 Crore
614            3.3 Crore
615           4.75 Crore
616            1.5 Crore
617           1.54 Crore
618           1.27 Crore
619           1.17 Crore
620            1.8 Crore
621               80 Lac
622           1.76 Crore
623           2.22 Crore
624           1.24 Crore
625           1.12 Crore
626            1.9 Crore
627           1.35 Crore
628           2.22 Crore
629               90 Lac
630           1.75 Crore
631            66.99 Lac
632           2.95 Crore
633           2.04 Crore
634           2.24 Crore
635           1.31 Crore
636            1.7 Crore
637           1.19 Crore
638           1.75 Crore
639           1.12 Crore
640               92 Lac
641               90 Lac
642            2.3 Crore
643           1.58 Crore
644           4.25 Crore
645           1.68 Crore
646           4.55 Crore
647           2.85 Crore
648           2.35 Crore
649            2.3 Crore
650           2.26 Crore
651           4.78 Crore
652              2 Crore
653           3.75 Crore
654           6.16 Crore
655            5.3 Crore
656               75 Lac
657           1.25 Crore
658              2 Crore
659            1.3 Crore
660           1.75 Crore
661              2 Crore
662           1.78 Crore
663           1.15 Crore
664           1.65 Crore
665               21 Lac
666           2.75 Crore
667           2.72 Crore
668            2.4 Crore
669            4.1 Crore
670           1.12 Crore
671               65 Lac
672            7.5 Crore
673             11 Crore
674           1.26 Crore
675            1.8 Crore
676            5.9 Crore
677            2.9 Crore
678           1.59 Crore
679           2.21 Crore
680           1.48 Crore
681               98 Lac
682           2.04 Crore
683            1.5 Crore
684           1.49 Crore
685            1.2 Crore
686               86 Lac
687             89.5 Lac
688              2 Crore
689           1.85 Crore
690           2.65 Crore
691            1.5 Crore
692           1.75 Crore
693           1.32 Crore
694               80 Lac
695            1.2 Crore
696            6.5 Crore
697           1.17 Crore
698           1.15 Crore
699           2.48 Crore
700           1.35 Crore
701           1.15 Crore
702           2.95 Crore
703            3.4 Crore
704            2.8 Crore
705           2.15 Crore
706           1.76 Crore
707           3.45 Crore
708            3.3 Crore
709           1.75 Crore
710           2.78 Crore
711           1.42 Crore
712            2.4 Crore
713           2.28 Crore
714            1.9 Crore
715           3.25 Crore
716            1.6 Crore
717           4.45 Crore
718               82 Lac
719               50 Lac
720               52 Lac
721               28 Lac
722               29 Lac
723               97 Lac
724               80 Lac
725           1.45 Crore
726               55 Lac
727            1.1 Crore
728            1.4 Crore
729           1.42 Crore
730           2.95 Crore
731            2.6 Crore
732            1.1 Crore
733               75 Lac
734            1.3 Crore
735           1.49 Crore
736           1.19 Crore
737           1.15 Crore
738             99.5 Lac
739               78 Lac
740           1.15 Crore
741               80 Lac
742            2.2 Crore
743           1.55 Crore
744           1.55 Crore
745               90 Lac
746               90 Lac
747               85 Lac
748              3 Crore
749           2.12 Crore
750           1.05 Crore
751           1.65 Crore
752            1.5 Crore
753            3.4 Crore
754            3.5 Crore
755           3.15 Crore
756           5.25 Crore
757           2.78 Crore
758               72 Lac
759           1.55 Crore
760            1.5 Crore
761           3.05 Crore
762           3.83 Crore
763           2.25 Crore
764            1.4 Crore
765           3.75 Crore
766           1.51 Crore
767            2.7 Crore
768           3.35 Crore
769            1.5 Crore
770            2.2 Crore
771           2.55 Crore
772               45 Lac
773           1.18 Crore
774               85 Lac
775           1.49 Crore
776            6.5 Crore
777           1.18 Crore
778               80 Lac
779           1.42 Crore
780              5 Crore
781           1.72 Crore
782           1.95 Crore
783               75 Lac
784           1.72 Crore
785            2.5 Crore
786            1.7 Crore
787           1.14 Crore
788           1.35 Crore
789             27.1 Lac
790            1.4 Crore
791           1.25 Crore
792           1.18 Crore
793            1.1 Crore
794           1.21 Crore
795           3.45 Crore
796           1.95 Crore
797           3.65 Crore

In [109]:
df[df['price'] == 'price']

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [110]:
df = df[df['price'] != 'Price on Request']
df = df[df['price'] != 'price']
df['price'].value_counts

<bound method IndexOpsMixin.value_counts of 0            45 Lac
1            50 Lac
2            40 Lac
3        1.47 Crore
4            70 Lac
5            41 Lac
6           2 Crore
7         1.8 Crore
8         1.1 Crore
9        4.75 Crore
10           96 Lac
11           29 Lac
12       1.35 Crore
13           95 Lac
14           70 Lac
15       3.95 Crore
16           90 Lac
17       1.05 Crore
18        2.2 Crore
19       1.01 Crore
20       1.85 Crore
21           86 Lac
22       1.85 Crore
23       2.85 Crore
25           42 Lac
26       6.15 Crore
27       6.25 Crore
28           42 Lac
29       1.35 Crore
30        1.6 Crore
31       3.25 Crore
32           45 Lac
33           85 Lac
34           75 Lac
35           82 Lac
36        1.8 Crore
37        29.99 Lac
38           78 Lac
39          2 Crore
40           74 Lac
41        3.2 Crore
42        1.3 Crore
43           25 Lac
44           95 Lac
45       1.99 Crore
46       1.05 Crore
47       1.83 Crore
48       2.25 Crore
49        2.8 Crore
50        1.6 Crore
51           83 Lac
52           83 Lac
53           80 Lac
54       1.25 Crore
55           23 Lac
56           30 Lac
57       1.55 Crore
58           79 Lac
59           50 Lac
60       1.01 Crore
61           95 Lac
62           99 Lac
63        1.1 Crore
64        1.9 Crore
65          1 Crore
66        2.5 Crore
67        1.1 Crore
68           29 Lac
69           55 Lac
70           65 Lac
71           50 Lac
72        31.75 Lac
73           93 Lac
74        1.2 Crore
75           30 Lac
76           56 Lac
77        2.7 Crore
78          1 Crore
79       1.45 Crore
80       1.25 Crore
81           46 Lac
82        4.5 Crore
83           64 Lac
84           28 Lac
85       3.87 Crore
86       1.38 Crore
87           43 Lac
88         28.5 Lac
89        1.1 Crore
90          2 Crore
91           90 Lac
92           90 Lac
93       1.75 Crore
94           93 Lac
95        1.8 Crore
96        2.1 Crore
97          2 Crore
98          2 Crore
99       1.29 Crore
100      2.85 Crore
101       1.1 Crore
102      1.65 Crore
103          24 Lac
104       2.1 Crore
105       1.9 Crore
106       1.1 Crore
107        31.5 Lac
108       1.7 Crore
109          32 Lac
110          45 Lac
111       1.2 Crore
112       2.1 Crore
113          45 Lac
114          42 Lac
115      1.55 Crore
116       1.3 Crore
117      2.75 Crore
118      1.25 Crore
119          42 Lac
120          40 Lac
121          34 Lac
122      1.25 Crore
123       1.5 Crore
124       1.3 Crore
125       1.6 Crore
126       1.5 Crore
127       1.5 Crore
128          90 Lac
129       1.5 Crore
130          80 Lac
131      1.25 Crore
132          26 Lac
133          42 Lac
134       2.5 Crore
135          90 Lac
136          42 Lac
137          50 Lac
138          90 Lac
139       1.3 Crore
140       1.7 Crore
141      1.25 Crore
142      2.91 Crore
143      1.15 Crore
144       1.2 Crore
145       1.5 Crore
146       1.3 Crore
147      1.75 Crore
148          55 Lac
149       2.5 Crore
150          43 Lac
151          80 Lac
152          45 Lac
153          70 Lac
154      1.95 Crore
155          45 Lac
156       1.7 Crore
157       1.1 Crore
158          50 Lac
159       2.8 Crore
160      1.45 Crore
161       2.2 Crore
162          90 Lac
163          40 Lac
164      1.35 Crore
165      1.85 Crore
166          25 Lac
167          88 Lac
168      1.15 Crore
169       1.6 Crore
170          85 Lac
171          75 Lac
172      3.35 Crore
173       1.5 Crore
174      1.65 Crore
175         2 Crore
176      1.75 Crore
177          90 Lac
178      1.25 Crore
179         1 Crore
180      1.08 Crore
181      2.15 Crore
182         1 Crore
183      1.65 Crore
184      1.79 Crore
185       1.8 Crore
186      1.45 Crore
187          22 Lac
188          36 Lac
189          25 Lac
190      1.15 Crore
191      1.65 Crore
192       2.9 Crore
193          60 Lac
194       2.4 Crore
195      1.25 Crore
196      2.15 Crore
197        29.5 Lac
198          38 Lac
199       1.5 Crore
200          39 Lac
201       1.6 Crore
202       1.7 Crore
203      3.25 Crore
204          60 Lac
205          27 Lac
206          95 Lac
207      2.65 Crore
208          36 Lac
209          55 Lac
210      1.32 Crore
211          59 Lac
212          45 Lac
213          90 Lac
214       1.4 Crore
215          95 Lac
216         3 Crore
217      3.67 Crore
218      3.85 Crore
219      3.29 Crore
220      2.33 Crore
221      2.79 Crore
222       3.4 Crore
223          72 Lac
224          40 Lac
225          56 Lac
226       1.1 Crore
227          71 Lac
228          78 Lac
229          40 Lac
230      1.85 Crore
231       1.1 Crore
232      1.41 Crore
233      1.45 Crore
234       2.2 Crore
235       1.1 Crore
236      2.05 Crore
237          60 Lac
238          80 Lac
239          41 Lac
240          90 Lac
241          54 Lac
242          82 Lac
243         1 Crore
244      1.85 Crore
245      1.42 Crore
246          55 Lac
247      2.29 Crore
248          97 Lac
249      8.25 Crore
250          30 Lac
251      1.65 Crore
252      1.99 Crore
253         1 Crore
254      4.25 Crore
255      1.25 Crore
256          95 Lac
257      1.05 Crore
258       4.1 Crore
259          50 Lac
260      1.65 Crore
261       1.6 Crore
262       2.1 Crore
263          90 Lac
264       1.1 Crore
265          92 Lac
266          70 Lac
267          99 Lac
268        71.5 Lac
269        87.5 Lac
270          91 Lac
271      1.25 Crore
272      1.05 Crore
273          66 Lac
274      1.83 Crore
275       52.56 Lac
276          80 Lac
277      1.71 Crore
278          65 Lac
279       1.3 Crore
280          82 Lac
281       5.7 Crore
282          88 Lac
283         4 Crore
284      1.93 Crore
285      3.45 Crore
286       1.7 Crore
287      6.15 Crore
288       1.4 Crore
289      1.48 Crore
290      3.25 Crore
291      1.49 Crore
292          30 Lac
293      3.49 Crore
294      2.15 Crore
295       1.4 Crore
296         2 Crore
297       2.3 Crore
298          54 Lac
299      1.25 Crore
300      1.05 Crore
301      1.25 Crore
302         1 Crore
303       1.7 Crore
304       1.3 Crore
305      2.12 Crore
306       3.9 Crore
307         3 Crore
308       2.2 Crore
309      1.35 Crore
310      1.67 Crore
311          90 Lac
312      2.37 Crore
313      1.98 Crore
314       3.7 Crore
315      4.67 Crore
316      1.29 Crore
317      3.65 Crore
318       1.7 Crore
319      6.15 Crore
320       1.4 Crore
321      1.48 Crore
322      3.49 Crore
323      2.15 Crore
324         2 Crore
325          54 Lac
326      1.25 Crore
327      1.05 Crore
328      1.25 Crore
329         1 Crore
330       1.7 Crore
331       1.3 Crore
332      2.12 Crore
333         3 Crore
334      1.35 Crore
335          90 Lac
336      1.98 Crore
337       3.7 Crore
338      1.29 Crore
339       5.6 Crore
340      1.25 Crore
341      1.27 Crore
342      1.36 Crore
343         1 Crore
344      4.25 Crore
345       1.8 Crore
346      1.25 Crore
347          27 Lac
348       5.5 Crore
349          85 Lac
350      1.07 Crore
351          95 Lac
352          87 Lac
353       4.1 Crore
354      1.27 Crore
355      1.47 Crore
356      3.45 Crore
357      1.18 Crore
358      1.55 Crore
359      3.39 Crore
360      1.54 Crore
361      1.42 Crore
362       1.3 Crore
363      2.25 Crore
364       3.5 Crore
365       4.8 Crore
366          78 Lac
367          88 Lac
368       2.6 Crore
369       3.4 Crore
370       2.9 Crore
371          70 Lac
372       1.5 Crore
373      1.28 Crore
374      2.51 Crore
375       6.5 Crore
376      3.63 Crore
377      1.85 Crore
378      2.45 Crore
379      1.38 Crore
380       5.9 Crore
381         3 Crore
382      2.01 Crore
383       2.1 Crore
384      4.25 Crore
385      2.55 Crore
386         2 Crore
387      3.25 Crore
388       1.6 Crore
389       1.5 Crore
390      3.75 Crore
391          95 Lac
392       1.4 Crore
393      1.56 Crore
394      1.35 Crore
395       1.4 Crore
396      2.26 Crore
397       1.2 Crore
398      2.08 Crore
399      1.75 Crore
400      2.99 Crore
401       2.1 Crore
402      2.87 Crore
403      2.35 Crore
404         3 Crore
405         6 Crore
406      2.35 Crore
407       1.9 Crore
408          72 Lac
409          65 Lac
410      2.34 Crore
411      2.57 Crore
412      1.71 Crore
413      3.79 Crore
414      2.05 Crore
415       5.2 Crore
416       3.2 Crore
417          69 Lac
418      3.75 Crore
419      3.65 Crore
420      5.49 Crore
421      1.05 Crore
422      3.35 Crore
423       2.4 Crore
424      1.71 Crore
425       6.3 Crore
426       2.2 Crore
427      3.25 Crore
428     11.25 Crore
429       3.3 Crore
430      1.51 Crore
431      1.38 Crore
432       4.6 Crore
433       1.4 Crore
434       3.5 Crore
435          99 Lac
436      2.65 Crore
437       2.4 Crore
438      1.65 Crore
439      1.25 Crore
440         4 Crore
441       1.8 Crore
442      1.75 Crore
443      2.35 Crore
444      7.15 Crore
445      1.64 Crore
446       2.8 Crore
447      6.75 Crore
448       3.5 Crore
449       4.6 Crore
450      2.25 Crore
451       2.2 Crore
452      2.85 Crore
453      1.76 Crore
454         1 Crore
455       3.6 Crore
456      1.78 Crore
457          98 Lac
458      2.82 Crore
459      3.21 Crore
460       1.9 Crore
461      1.19 Crore
462      1.35 Crore
463       1.8 Crore
464      1.35 Crore
465       1.7 Crore
466       1.6 Crore
467      2.65 Crore
468       54.99 Lac
469       1.4 Crore
470      1.26 Crore
471       1.7 Crore
472       4.1 Crore
473      1.01 Crore
474      1.45 Crore
475       1.6 Crore
476      2.99 Crore
477       1.9 Crore
478      1.75 Crore
479       1.3 Crore
480      2.95 Crore
481       3.4 Crore
482      3.32 Crore
483          95 Lac
484      1.55 Crore
485      1.54 Crore
486      2.45 Crore
487       2.6 Crore
488      1.83 Crore
489      1.09 Crore
490      1.87 Crore
491      1.05 Crore
492      1.77 Crore
493       2.2 Crore
494          60 Lac
495       1.8 Crore
496          64 Lac
497          75 Lac
498      4.95 Crore
499      4.25 Crore
500      5.31 Crore
501       1.4 Crore
502       2.8 Crore
503       4.1 Crore
504       3.4 Crore
505      3.05 Crore
506      4.25 Crore
507      1.16 Crore
508      3.55 Crore
509       1.8 Crore
510      1.75 Crore
511       1.2 Crore
512      1.52 Crore
513      1.55 Crore
514       2.4 Crore
515      2.35 Crore
516      2.28 Crore
517       1.1 Crore
518       2.3 Crore
519      1.35 Crore
520      2.45 Crore
521          90 Lac
522       2.8 Crore
523       1.4 Crore
524      1.36 Crore
525        98.5 Lac
526        56.2 Lac
527       2.2 Crore
528       1.2 Crore
529      1.33 Crore
530          87 Lac
531      1.09 Crore
532         3 Crore
533      1.75 Crore
534      1.75 Crore
535       3.8 Crore
536       3.5 Crore
537      1.78 Crore
538      1.08 Crore
539      2.03 Crore
540      1.12 Crore
541         2 Crore
542      1.04 Crore
543      1.25 Crore
544      2.05 Crore
545      3.19 Crore
546      3.85 Crore
547       3.2 Crore
548        88.5 Lac
549          49 Lac
550      1.65 Crore
551      2.35 Crore
552       1.4 Crore
553          97 Lac
554      2.35 Crore
555      3.32 Crore
556      1.25 Crore
557       2.8 Crore
558       4.7 Crore
559       1.3 Crore
560          62 Lac
561          80 Lac
562      1.73 Crore
563      4.45 Crore
564       2.3 Crore
565       2.2 Crore
566      2.12 Crore
567      2.25 Crore
568       1.9 Crore
569       4.4 Crore
570      1.75 Crore
571       2.8 Crore
572      4.63 Crore
573      1.32 Crore
574      1.16 Crore
575          27 Lac
576       27.75 Lac
577      1.79 Crore
578      1.55 Crore
579      1.55 Crore
580      3.35 Crore
581       3.5 Crore
582       4.8 Crore
583       1.5 Crore
584      2.78 Crore
585      2.25 Crore
586      2.55 Crore
587      1.25 Crore
588          85 Lac
589      5.25 Crore
590       1.3 Crore
591          75 Lac
592      3.65 Crore
593      1.65 Crore
594      1.25 Crore
595      1.42 Crore
596      1.27 Crore
597      1.65 Crore
598      1.24 Crore
599       2.7 Crore
600      1.98 Crore
601       2.5 Crore
602      2.29 Crore
603      2.98 Crore
604      1.35 Crore
605      1.37 Crore
606      1.55 Crore
607      4.25 Crore
608      1.28 Crore
609      1.95 Crore
610      2.35 Crore
611         5 Crore
612          99 Lac
613      1.95 Crore
614       3.3 Crore
615      4.75 Crore
616       1.5 Crore
617      1.54 Crore
618      1.27 Crore
619      1.17 Crore
620       1.8 Crore
621          80 Lac
622      1.76 Crore
623      2.22 Crore
624      1.24 Crore
625      1.12 Crore
626       1.9 Crore
627      1.35 Crore
628      2.22 Crore
629          90 Lac
630      1.75 Crore
631       66.99 Lac
632      2.95 Crore
633      2.04 Crore
634      2.24 Crore
635      1.31 Crore
636       1.7 Crore
637      1.19 Crore
638      1.75 Crore
639      1.12 Crore
640          92 Lac
641          90 Lac
642       2.3 Crore
643      1.58 Crore
644      4.25 Crore
645      1.68 Crore
646      4.55 Crore
647      2.85 Crore
648      2.35 Crore
649       2.3 Crore
650      2.26 Crore
651      4.78 Crore
652         2 Crore
653      3.75 Crore
654      6.16 Crore
655       5.3 Crore
656          75 Lac
657      1.25 Crore
658         2 Crore
659       1.3 Crore
660      1.75 Crore
661         2 Crore
662      1.78 Crore
663      1.15 Crore
664      1.65 Crore
665          21 Lac
666      2.75 Crore
667      2.72 Crore
668       2.4 Crore
669       4.1 Crore
670      1.12 Crore
671          65 Lac
672       7.5 Crore
673        11 Crore
674      1.26 Crore
675       1.8 Crore
676       5.9 Crore
677       2.9 Crore
678      1.59 Crore
679      2.21 Crore
680      1.48 Crore
681          98 Lac
682      2.04 Crore
683       1.5 Crore
684      1.49 Crore
685       1.2 Crore
686          86 Lac
687        89.5 Lac
688         2 Crore
689      1.85 Crore
690      2.65 Crore
691       1.5 Crore
692      1.75 Crore
693      1.32 Crore
694          80 Lac
695       1.2 Crore
696       6.5 Crore
697      1.17 Crore
698      1.15 Crore
699      2.48 Crore
700      1.35 Crore
701      1.15 Crore
702      2.95 Crore
703       3.4 Crore
704       2.8 Crore
705      2.15 Crore
706      1.76 Crore
707      3.45 Crore
708       3.3 Crore
709      1.75 Crore
710      2.78 Crore
711      1.42 Crore
712       2.4 Crore
713      2.28 Crore
714       1.9 Crore
715      3.25 Crore
716       1.6 Crore
717      4.45 Crore
718          82 Lac
719          50 Lac
720          52 Lac
721          28 Lac
722          29 Lac
723          97 Lac
724          80 Lac
725      1.45 Crore
726          55 Lac
727       1.1 Crore
728       1.4 Crore
729      1.42 Crore
730      2.95 Crore
731       2.6 Crore
732       1.1 Crore
733          75 Lac
734       1.3 Crore
735      1.49 Crore
736      1.19 Crore
737      1.15 Crore
738        99.5 Lac
739          78 Lac
740      1.15 Crore
741          80 Lac
742       2.2 Crore
743      1.55 Crore
744      1.55 Crore
745          90 Lac
746          90 Lac
747          85 Lac
748         3 Crore
749      2.12 Crore
750      1.05 Crore
751      1.65 Crore
752       1.5 Crore
753       3.4 Crore
754       3.5 Crore
755      3.15 Crore
756      5.25 Crore
757      2.78 Crore
758          72 Lac
759      1.55 Crore
760       1.5 Crore
761      3.05 Crore
762      3.83 Crore
763      2.25 Crore
764       1.4 Crore
765      3.75 Crore
766      1.51 Crore
767       2.7 Crore
768      3.35 Crore
769       1.5 Crore
770       2.2 Crore
771      2.55 Crore
772          45 Lac
773      1.18 Crore
774          85 Lac
775      1.49 Crore
776       6.5 Crore
777      1.18 Crore
778          80 Lac
779      1.42 Crore
780         5 Crore
781      1.72 Crore
782      1.95 Crore
783          75 Lac
784      1.72 Crore
785       2.5 Crore
786       1.7 Crore
787      1.14 Crore
788      1.35 Crore
789        27.1 Lac
790       1.4 Crore
791      1.25 Crore
792      1.18 Crore
793       1.1 Crore
794      1.21 Crore
795      3.45 Crore
796      1.95 Crore
797      3.65 Crore
798       2.3 Crore
799       3.4 Crore
800      1.14 Crore
801       95.75 Lac
802      3.05 Crore
803      2.35 Crore
804      1.05 Crore
805      1.02 Crore
806      1.08 Crore
807      1.75 Crore
808      2.45 Crore
809         6 Crore
810      1.68 Crore
811      1.26 Crore
812      1.82 Crore
813      2.58 Crore
814      1.75 Crore
815       2.6 Crore
816       2.9 Crore
817       1.4 Crore
818      2.95 Crore
819      2.25 Crore
820       1.4 Crore
821      1.26 Crore
822       1.7 Crore
823      1.43 Crore
824       1.3 Crore
825      1.32 Crore
826         2 Crore
827      1.43 Crore
828      3.46 Crore
829      2.25 Crore
830       1.7 Crore
831       1.8 Crore
832      1.35 Crore
833       5.4 Crore
834      1.55 Crore
835       1.6 Crore
836      2.09 Crore
837      1.75 Crore
838      1.38 Crore
839      2.25 Crore
840       2.4 Crore
841      1.72 Crore
842          88 Lac
843      3.15 Crore
844      1.72 Crore
845      1.47 Crore
846       1.1 Crore
847      1.32 Crore
848       1.3 Crore
849      1.35 Crore
850         3 Crore
851       1.6 Crore
852         3 Crore
853          90 Lac
854      1.75 Crore
855         2 Crore
856       1.8 Crore
857       1.6 Crore
858       1.4 Crore
859       1.8 Crore
860       2.7 Crore
861      1.55 Crore
862      1.15 Crore
863      1.49 Crore
864      1.91 Crore
865      1.05 Crore
866      2.14 Crore
867      1.02 Crore
868        55.6 Lac
869       2.5 Crore
870         2 Crore
871       2.2 Crore
872      1.65 Crore
873       1.6 Crore
874          85 Lac
875       1.4 Crore
876      2.09 Crore
877      2.51 Crore
878      1.69 Crore
879        98.1 Lac
880         2 Crore
881      1.95 Crore
882       2.1 Crore
883      1.55 Crore
884      1.98 Crore
885      2.05 Crore
886       1.4 Crore
887       1.4 Crore
888      2.36 Crore
889      1.65 Crore
890      2.65 Crore
891      2.63 Crore
892      2.25 Crore
893      2.55 Crore
894      1.15 Crore
895      1.45 Crore
896       2.6 Crore
897      1.55 Crore
898       1.2 Crore
899      1.55 Crore
900      1.65 Crore
901      1.05 Crore
902      1.29 Crore
903        55.5 Lac
904      1.26 Crore
905      1.91 Crore
906       2.2 Crore
907      1.98 Crore
908      1.11 Crore
909      2.25 Crore
910      1.05 Crore
911       2.6 Crore
912      1.04 Crore
913      1.25 Crore
914       3.4 Crore
915      1.25 Crore
916        41.5 Lac
917          75 Lac
918       1.7 Crore
919          87 Lac
920      1.25 Crore
921      2.35 Crore
922      1.73 Crore
923          97 Lac
924      1.35 Crore
925      1.32 Crore
926        71.5 Lac
927          78 Lac
928       5.5 Crore
929       2.3 Crore
930          43 Lac
931        98.5 Lac
932          80 Lac
933      2.65 Crore
934      2.35 Crore
935      1.29 Crore
936      1.83 Crore
937      1.39 Crore
938      1.12 Crore
939          65 Lac
940       1.5 Crore
941       1.9 Crore
942      2.35 Crore
943          60 Lac
944         2 Crore
945      1.57 Crore
946      1.44 Crore
947      1.26 Crore
948      1.05 Crore
949      6.44 Crore
950      7.56 Crore
951       3.8 Crore
952      6.75 Crore
953        64.5 Lac
954      1.75 Crore
955      1.54 Crore
956       1.4 Crore
957          97 Lac
958      1.35 Crore
959      1.75 Crore
960       2.2 Crore
961      2.45 Crore
962       1.5 Crore
963       2.4 Crore
964      2.45 Crore
965         3 Crore
966      1.65 Crore
967          88 Lac
968          88 Lac
969      1.28 Crore
970      1.34 Crore
971      1.32 Crore
972      1.13 Crore
973      1.38 Crore
974      1.16 Crore
975      2.33 Crore
976      3.05 Crore
977      1.25 Crore
978      1.25 Crore
979      1.05 Crore
980      1.25 Crore
981       1.1 Crore
982       1.3 Crore
983      2.28 Crore
984       1.2 Crore
985      1.22 Crore
986       1.1 Crore
987      1.15 Crore
988       1.2 Crore
989       1.4 Crore
990       1.1 Crore
991         1 Crore
992      1.52 Crore
993       1.8 Crore
994       1.6 Crore
995      1.55 Crore
996       1.3 Crore
997      2.25 Crore

In [111]:
def price_convertor(x):
    if type(x) == float:
        return x
    else:
        if x[1] == 'Lac':
            return round(float(x[0])/100,2)
        else:
            return round(float(x[0]),2)

In [112]:
df['price'] = df['price'].str.split(' ').apply(price_convertor)

In [113]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [114]:
df['price_per_sqft'].value_counts

<bound method IndexOpsMixin.value_counts of 0         ₹ 5,000/sq.ft.
1         ₹ 7,692/sq.ft.
2         ₹ 6,722/sq.ft.
3        ₹ 12,250/sq.ft.
4         ₹ 5,204/sq.ft.
5         ₹ 6,269/sq.ft.
6        ₹ 13,333/sq.ft.
7         ₹ 7,860/sq.ft.
8         ₹ 8,148/sq.ft.
9        ₹ 16,885/sq.ft.
10        ₹ 9,767/sq.ft.
11        ₹ 5,587/sq.ft.
12        ₹ 6,940/sq.ft.
13        ₹ 6,859/sq.ft.
14        ₹ 5,384/sq.ft.
15       ₹ 16,859/sq.ft.
16       ₹ 14,084/sq.ft.
17       ₹ 11,475/sq.ft.
18       ₹ 10,476/sq.ft.
19        ₹ 9,156/sq.ft.
20        ₹ 8,604/sq.ft.
21        ₹ 7,796/sq.ft.
22        ₹ 9,135/sq.ft.
23       ₹ 12,855/sq.ft.
25        ₹ 7,910/sq.ft.
26       ₹ 18,331/sq.ft.
27       ₹ 24,300/sq.ft.
28        ₹ 5,600/sq.ft.
29       ₹ 12,784/sq.ft.
30       ₹ 26,936/sq.ft.
31       ₹ 10,156/sq.ft.
32        ₹ 7,194/sq.ft.
33        ₹ 6,538/sq.ft.
34        ₹ 5,769/sq.ft.
35        ₹ 6,950/sq.ft.
36        ₹ 8,866/sq.ft.
37        ₹ 5,403/sq.ft.
38        ₹ 5,714/sq.ft.
39       ₹ 15,151/sq.ft.
40        ₹ 6,200/sq.ft.
41       ₹ 16,000/sq.ft.
42        ₹ 6,378/sq.ft.
43        ₹ 3,571/sq.ft.
44        ₹ 7,846/sq.ft.
45        ₹ 7,297/sq.ft.
46        ₹ 7,581/sq.ft.
47       ₹ 10,005/sq.ft.
48       ₹ 10,714/sq.ft.
49       ₹ 16,969/sq.ft.
50       ₹ 14,545/sq.ft.
51        ₹ 5,424/sq.ft.
52        ₹ 7,410/sq.ft.
53        ₹ 6,400/sq.ft.
54        ₹ 4,715/sq.ft.
55        ₹ 5,000/sq.ft.
56        ₹ 6,666/sq.ft.
57        ₹ 9,872/sq.ft.
58        ₹ 6,594/sq.ft.
59        ₹ 5,555/sq.ft.
60        ₹ 7,000/sq.ft.
61        ₹ 5,007/sq.ft.
62        ₹ 7,857/sq.ft.
63        ₹ 6,376/sq.ft.
64        ₹ 8,863/sq.ft.
65        ₹ 4,320/sq.ft.
66       ₹ 11,111/sq.ft.
67       ₹ 10,410/sq.ft.
68        ₹ 5,178/sq.ft.
69        ₹ 5,556/sq.ft.
70        ₹ 4,744/sq.ft.
71        ₹ 9,406/sq.ft.
72        ₹ 5,521/sq.ft.
73        ₹ 6,404/sq.ft.
74        ₹ 8,432/sq.ft.
75        ₹ 4,687/sq.ft.
76        ₹ 6,812/sq.ft.
77       ₹ 12,505/sq.ft.
78        ₹ 5,128/sq.ft.
79       ₹ 11,153/sq.ft.
80        ₹ 8,784/sq.ft.
81           ₹ 79/sq.ft.
82       ₹ 10,599/sq.ft.
83        ₹ 6,500/sq.ft.
84        ₹ 3,768/sq.ft.
85       ₹ 17,200/sq.ft.
86        ₹ 6,338/sq.ft.
87        ₹ 6,615/sq.ft.
88        ₹ 3,166/sq.ft.
89        ₹ 9,838/sq.ft.
90       ₹ 13,957/sq.ft.
91        ₹ 8,035/sq.ft.
92        ₹ 8,036/sq.ft.
93        ₹ 8,768/sq.ft.
94        ₹ 8,611/sq.ft.
95        ₹ 6,600/sq.ft.
96       ₹ 11,738/sq.ft.
97       ₹ 14,492/sq.ft.
98       ₹ 12,800/sq.ft.
99        ₹ 7,800/sq.ft.
100      ₹ 15,590/sq.ft.
101       ₹ 5,641/sq.ft.
102      ₹ 13,750/sq.ft.
103       ₹ 7,407/sq.ft.
104      ₹ 10,500/sq.ft.
105       ₹ 9,849/sq.ft.
106      ₹ 11,482/sq.ft.
107       ₹ 4,500/sq.ft.
108      ₹ 17,617/sq.ft.
109       ₹ 6,106/sq.ft.
110       ₹ 7,739/sq.ft.
111      ₹ 10,018/sq.ft.
112      ₹ 16,030/sq.ft.
113           ₹ 7/sq.ft.
114       ₹ 5,600/sq.ft.
115       ₹ 9,955/sq.ft.
116       ₹ 9,027/sq.ft.
117      ₹ 10,589/sq.ft.
118       ₹ 6,443/sq.ft.
119       ₹ 7,407/sq.ft.
120       ₹ 6,420/sq.ft.
121       ₹ 5,405/sq.ft.
122       ₹ 8,784/sq.ft.
123      ₹ 12,744/sq.ft.
124       ₹ 9,285/sq.ft.
125       ₹ 8,000/sq.ft.
126      ₹ 11,755/sq.ft.
127      ₹ 11,755/sq.ft.
128       ₹ 7,149/sq.ft.
129       ₹ 9,146/sq.ft.
130      ₹ 13,115/sq.ft.
131       ₹ 7,396/sq.ft.
132       ₹ 5,397/sq.ft.
133       ₹ 7,909/sq.ft.
134      ₹ 12,920/sq.ft.
135       ₹ 4,615/sq.ft.
136       ₹ 7,106/sq.ft.
137       ₹ 7,692/sq.ft.
138       ₹ 5,883/sq.ft.
139       ₹ 6,806/sq.ft.
140       ₹ 9,502/sq.ft.
141       ₹ 6,200/sq.ft.
142       ₹ 6,700/sq.ft.
143       ₹ 5,750/sq.ft.
144      ₹ 12,526/sq.ft.
145      ₹ 12,244/sq.ft.
146       ₹ 7,424/sq.ft.
147      ₹ 10,361/sq.ft.
148       ₹ 6,470/sq.ft.
149      ₹ 13,600/sq.ft.
150       ₹ 5,308/sq.ft.
151       ₹ 5,556/sq.ft.
152       ₹ 4,500/sq.ft.
153       ₹ 4,666/sq.ft.
154      ₹ 14,444/sq.ft.
155       ₹ 7,188/sq.ft.
156      ₹ 10,828/sq.ft.
157       ₹ 6,111/sq.ft.
158       ₹ 9,615/sq.ft.
159      ₹ 15,000/sq.ft.
160      ₹ 15,664/sq.ft.
161      ₹ 13,496/sq.ft.
162       ₹ 9,463/sq.ft.
163       ₹ 7,782/sq.ft.
164       ₹ 7,780/sq.ft.
165       ₹ 8,043/sq.ft.
166       ₹ 6,578/sq.ft.
167       ₹ 7,963/sq.ft.
168       ₹ 6,593/sq.ft.
169      ₹ 12,185/sq.ft.
170       ₹ 6,789/sq.ft.
171       ₹ 7,500/sq.ft.
172       ₹ 7,444/sq.ft.
173       ₹ 8,108/sq.ft.
174       ₹ 6,345/sq.ft.
175       ₹ 6,967/sq.ft.
176       ₹ 6,250/sq.ft.
177       ₹ 7,627/sq.ft.
178       ₹ 6,703/sq.ft.
179       ₹ 6,506/sq.ft.
180       ₹ 6,150/sq.ft.
181       ₹ 8,928/sq.ft.
182      ₹ 12,106/sq.ft.
183      ₹ 13,074/sq.ft.
184       ₹ 8,081/sq.ft.
185      ₹ 13,136/sq.ft.
186      ₹ 10,139/sq.ft.
187       ₹ 4,731/sq.ft.
188       ₹ 5,142/sq.ft.
189       ₹ 4,258/sq.ft.
190       ₹ 7,496/sq.ft.
191      ₹ 17,441/sq.ft.
192      ₹ 12,619/sq.ft.
193       ₹ 4,546/sq.ft.
194      ₹ 10,000/sq.ft.
195       ₹ 9,904/sq.ft.
196      ₹ 15,003/sq.ft.
197       ₹ 3,970/sq.ft.
198       ₹ 5,067/sq.ft.
199      ₹ 12,500/sq.ft.
200       ₹ 4,105/sq.ft.
201       ₹ 6,667/sq.ft.
202       ₹ 8,504/sq.ft.
203      ₹ 14,118/sq.ft.
204       ₹ 8,450/sq.ft.
205       ₹ 2,700/sq.ft.
206       ₹ 8,886/sq.ft.
207      ₹ 18,492/sq.ft.
208       ₹ 7,643/sq.ft.
209       ₹ 9,166/sq.ft.
210      ₹ 16,923/sq.ft.
211       ₹ 3,975/sq.ft.
212       ₹ 4,705/sq.ft.
213       ₹ 6,225/sq.ft.
214      ₹ 10,000/sq.ft.
215       ₹ 6,542/sq.ft.
216      ₹ 18,000/sq.ft.
217      ₹ 17,990/sq.ft.
218       ₹ 7,500/sq.ft.
219      ₹ 17,997/sq.ft.
220      ₹ 18,477/sq.ft.
221      ₹ 14,168/sq.ft.
222      ₹ 11,724/sq.ft.
223       ₹ 7,272/sq.ft.
224       ₹ 7,036/sq.ft.
225       ₹ 4,105/sq.ft.
226       ₹ 6,790/sq.ft.
227       ₹ 5,420/sq.ft.
228       ₹ 6,024/sq.ft.
229       ₹ 5,882/sq.ft.
230      ₹ 11,716/sq.ft.
231      ₹ 12,181/sq.ft.
232      ₹ 12,250/sq.ft.
233       ₹ 7,455/sq.ft.
234      ₹ 13,500/sq.ft.
235       ₹ 9,909/sq.ft.
236       ₹ 9,876/sq.ft.
237       ₹ 5,000/sq.ft.
238       ₹ 4,820/sq.ft.
239       ₹ 7,032/sq.ft.
240       ₹ 5,548/sq.ft.
241       ₹ 5,888/sq.ft.
242       ₹ 7,585/sq.ft.
243       ₹ 6,734/sq.ft.
244       ₹ 9,024/sq.ft.
245       ₹ 8,000/sq.ft.
246       ₹ 9,166/sq.ft.
247      ₹ 15,980/sq.ft.
248      ₹ 10,601/sq.ft.
249      ₹ 28,000/sq.ft.
250       ₹ 4,444/sq.ft.
251      ₹ 14,335/sq.ft.
252      ₹ 15,793/sq.ft.
253      ₹ 12,500/sq.ft.
254      ₹ 26,562/sq.ft.
255       ₹ 5,000/sq.ft.
256       ₹ 6,300/sq.ft.
257       ₹ 7,777/sq.ft.
258      ₹ 14,100/sq.ft.
259       ₹ 6,983/sq.ft.
260       ₹ 5,892/sq.ft.
261      ₹ 10,158/sq.ft.
262      ₹ 13,750/sq.ft.
263       ₹ 3,648/sq.ft.
264       ₹ 7,772/sq.ft.
265       ₹ 6,739/sq.ft.
266       ₹ 5,556/sq.ft.
267       ₹ 6,325/sq.ft.
268       ₹ 6,061/sq.ft.
269       ₹ 6,429/sq.ft.
270       ₹ 6,862/sq.ft.
271       ₹ 6,377/sq.ft.
272      ₹ 10,531/sq.ft.
273       ₹ 5,038/sq.ft.
274      ₹ 13,969/sq.ft.
275       ₹ 4,800/sq.ft.
276       ₹ 5,797/sq.ft.
277      ₹ 12,000/sq.ft.
278       ₹ 9,286/sq.ft.
279       ₹ 6,510/sq.ft.
280       ₹ 5,384/sq.ft.
281      ₹ 41,245/sq.ft.
282      ₹ 10,945/sq.ft.
283       ₹ 9,851/sq.ft.
284       ₹ 8,075/sq.ft.
285      ₹ 13,269/sq.ft.
286       ₹ 7,727/sq.ft.
287      ₹ 15,998/sq.ft.
288       ₹ 7,865/sq.ft.
289       ₹ 7,400/sq.ft.
290       ₹ 7,510/sq.ft.
291       ₹ 8,514/sq.ft.
292       ₹ 4,599/sq.ft.
293      ₹ 13,000/sq.ft.
294      ₹ 14,257/sq.ft.
295       ₹ 9,333/sq.ft.
296      ₹ 14,214/sq.ft.
297      ₹ 14,110/sq.ft.
298       ₹ 7,248/sq.ft.
299       ₹ 6,921/sq.ft.
300      ₹ 10,603/sq.ft.
301       ₹ 8,620/sq.ft.
302       ₹ 9,090/sq.ft.
303       ₹ 7,391/sq.ft.
304       ₹ 4,666/sq.ft.
305      ₹ 16,960/sq.ft.
306      ₹ 33,209/sq.ft.
307      ₹ 11,516/sq.ft.
308      ₹ 14,202/sq.ft.
309       ₹ 8,181/sq.ft.
310      ₹ 10,500/sq.ft.
311       ₹ 6,666/sq.ft.
312      ₹ 11,500/sq.ft.
313       ₹ 9,900/sq.ft.
314      ₹ 17,619/sq.ft.
315      ₹ 17,000/sq.ft.
316       ₹ 8,206/sq.ft.
317      ₹ 15,240/sq.ft.
318       ₹ 7,727/sq.ft.
319      ₹ 15,998/sq.ft.
320       ₹ 7,865/sq.ft.
321       ₹ 7,400/sq.ft.
322      ₹ 13,000/sq.ft.
323      ₹ 14,257/sq.ft.
324      ₹ 14,214/sq.ft.
325       ₹ 7,248/sq.ft.
326       ₹ 6,921/sq.ft.
327      ₹ 10,603/sq.ft.
328       ₹ 8,620/sq.ft.
329       ₹ 9,090/sq.ft.
330       ₹ 7,391/sq.ft.
331       ₹ 4,666/sq.ft.
332      ₹ 16,960/sq.ft.
333      ₹ 11,516/sq.ft.
334       ₹ 8,181/sq.ft.
335       ₹ 6,666/sq.ft.
336       ₹ 9,900/sq.ft.
337      ₹ 17,619/sq.ft.
338       ₹ 8,206/sq.ft.
339      ₹ 19,363/sq.ft.
340       ₹ 5,832/sq.ft.
341       ₹ 9,777/sq.ft.
342       ₹ 6,542/sq.ft.
343       ₹ 8,160/sq.ft.
344       ₹ 9,334/sq.ft.
345       ₹ 9,473/sq.ft.
346       ₹ 6,597/sq.ft.
347       ₹ 5,897/sq.ft.
348      ₹ 18,181/sq.ft.
349       ₹ 4,271/sq.ft.
350       ₹ 7,725/sq.ft.
351      ₹ 10,895/sq.ft.
352      ₹ 11,845/sq.ft.
353      ₹ 23,401/sq.ft.
354       ₹ 9,182/sq.ft.
355      ₹ 12,782/sq.ft.
356      ₹ 15,681/sq.ft.
357       ₹ 7,539/sq.ft.
358       ₹ 8,072/sq.ft.
359      ₹ 14,376/sq.ft.
360       ₹ 9,221/sq.ft.
361       ₹ 8,606/sq.ft.
362      ₹ 10,000/sq.ft.
363      ₹ 14,516/sq.ft.
364      ₹ 14,583/sq.ft.
365      ₹ 19,200/sq.ft.
366       ₹ 8,047/sq.ft.
367       ₹ 4,888/sq.ft.
368      ₹ 10,007/sq.ft.
369      ₹ 13,765/sq.ft.
370      ₹ 14,478/sq.ft.
371       ₹ 4,651/sq.ft.
372       ₹ 9,740/sq.ft.
373       ₹ 9,552/sq.ft.
374      ₹ 14,800/sq.ft.
375      ₹ 18,571/sq.ft.
376      ₹ 14,500/sq.ft.
377       ₹ 8,604/sq.ft.
378       ₹ 8,521/sq.ft.
379       ₹ 6,509/sq.ft.
380      ₹ 11,028/sq.ft.
381       ₹ 6,134/sq.ft.
382      ₹ 11,426/sq.ft.
383      ₹ 11,938/sq.ft.
384      ₹ 13,281/sq.ft.
385      ₹ 12,318/sq.ft.
386       ₹ 8,510/sq.ft.
387      ₹ 12,810/sq.ft.
388       ₹ 7,825/sq.ft.
389       ₹ 7,825/sq.ft.
390      ₹ 14,938/sq.ft.
391       ₹ 6,709/sq.ft.
392      ₹ 10,769/sq.ft.
393       ₹ 8,087/sq.ft.
394       ₹ 8,181/sq.ft.
395      ₹ 10,378/sq.ft.
396      ₹ 13,696/sq.ft.
397       ₹ 8,043/sq.ft.
398      ₹ 10,000/sq.ft.
399       ₹ 7,267/sq.ft.
400      ₹ 11,832/sq.ft.
401      ₹ 14,254/sq.ft.
402      ₹ 11,903/sq.ft.
403      ₹ 13,224/sq.ft.
404      ₹ 12,000/sq.ft.
405      ₹ 13,636/sq.ft.
406      ₹ 14,242/sq.ft.
407       ₹ 5,681/sq.ft.
408       ₹ 4,881/sq.ft.
409       ₹ 4,259/sq.ft.
410      ₹ 11,185/sq.ft.
411      ₹ 15,575/sq.ft.
412       ₹ 7,804/sq.ft.
413       ₹ 9,895/sq.ft.
414       ₹ 7,884/sq.ft.
415      ₹ 17,455/sq.ft.
416      ₹ 17,777/sq.ft.
417       ₹ 7,272/sq.ft.
418      ₹ 13,383/sq.ft.
419      ₹ 12,312/sq.ft.
420      ₹ 11,584/sq.ft.
421       ₹ 5,011/sq.ft.
422      ₹ 13,266/sq.ft.
423      ₹ 11,505/sq.ft.
424       ₹ 7,600/sq.ft.
425      ₹ 15,384/sq.ft.
426       ₹ 9,490/sq.ft.
427       ₹ 9,558/sq.ft.
428      ₹ 28,266/sq.ft.
429      ₹ 13,750/sq.ft.
430       ₹ 7,869/sq.ft.
431      ₹ 13,495/sq.ft.
432      ₹ 18,400/sq.ft.
433       ₹ 8,484/sq.ft.
434      ₹ 17,721/sq.ft.
435       ₹ 5,530/sq.ft.
436      ₹ 16,060/sq.ft.
437      ₹ 12,346/sq.ft.
438       ₹ 7,674/sq.ft.
439       ₹ 6,921/sq.ft.
440      ₹ 14,871/sq.ft.
441       ₹ 9,473/sq.ft.
442      ₹ 11,121/sq.ft.
443      ₹ 14,242/sq.ft.
444      ₹ 16,486/sq.ft.
445       ₹ 8,410/sq.ft.
446      ₹ 16,969/sq.ft.
447      ₹ 21,360/sq.ft.
448      ₹ 14,583/sq.ft.
449      ₹ 26,790/sq.ft.
450      ₹ 12,500/sq.ft.
451      ₹ 10,516/sq.ft.
452      ₹ 10,936/sq.ft.
453       ₹ 7,945/sq.ft.
454       ₹ 7,220/sq.ft.
455      ₹ 12,627/sq.ft.
456       ₹ 7,392/sq.ft.
457       ₹ 6,049/sq.ft.
458      ₹ 12,818/sq.ft.
459      ₹ 16,050/sq.ft.
460      ₹ 18,500/sq.ft.
461       ₹ 5,505/sq.ft.
462       ₹ 7,541/sq.ft.
463       ₹ 9,000/sq.ft.
464       ₹ 7,541/sq.ft.
465       ₹ 6,679/sq.ft.
466       ₹ 6,597/sq.ft.
467      ₹ 13,125/sq.ft.
468       ₹ 5,788/sq.ft.
469      ₹ 13,690/sq.ft.
470       ₹ 8,051/sq.ft.
471       ₹ 6,141/sq.ft.
472      ₹ 28,101/sq.ft.
473       ₹ 8,080/sq.ft.
474       ₹ 7,260/sq.ft.
475       ₹ 8,376/sq.ft.
476      ₹ 14,950/sq.ft.
477       ₹ 9,783/sq.ft.
478      ₹ 12,544/sq.ft.
479       ₹ 7,150/sq.ft.
480      ₹ 12,235/sq.ft.
481      ₹ 14,418/sq.ft.
482      ₹ 14,079/sq.ft.
483       ₹ 6,713/sq.ft.
484      ₹ 13,790/sq.ft.
485      ₹ 10,814/sq.ft.
486      ₹ 12,140/sq.ft.
487      ₹ 15,160/sq.ft.
488       ₹ 7,610/sq.ft.
489       ₹ 6,661/sq.ft.
490       ₹ 7,780/sq.ft.
491       ₹ 6,163/sq.ft.
492       ₹ 7,350/sq.ft.
493      ₹ 10,901/sq.ft.
494       ₹ 8,163/sq.ft.
495       ₹ 6,000/sq.ft.
496       ₹ 4,193/sq.ft.
497       ₹ 3,309/sq.ft.
498      ₹ 15,906/sq.ft.
499      ₹ 11,294/sq.ft.
500      ₹ 11,204/sq.ft.
501       ₹ 8,484/sq.ft.
502      ₹ 11,470/sq.ft.
503      ₹ 10,567/sq.ft.
504      ₹ 10,000/sq.ft.
505      ₹ 12,788/sq.ft.
506      ₹ 13,076/sq.ft.
507       ₹ 6,987/sq.ft.
508       ₹ 6,826/sq.ft.
509       ₹ 9,528/sq.ft.
510      ₹ 15,514/sq.ft.
511      ₹ 14,563/sq.ft.
512       ₹ 9,212/sq.ft.
513       ₹ 6,888/sq.ft.
514      ₹ 11,412/sq.ft.
515      ₹ 11,174/sq.ft.
516      ₹ 10,841/sq.ft.
517       ₹ 4,857/sq.ft.
518      ₹ 10,936/sq.ft.
519       ₹ 5,717/sq.ft.
520      ₹ 10,000/sq.ft.
521       ₹ 5,867/sq.ft.
522      ₹ 14,177/sq.ft.
523      ₹ 10,174/sq.ft.
524       ₹ 7,646/sq.ft.
525       ₹ 6,961/sq.ft.
526       ₹ 8,632/sq.ft.
527       ₹ 7,586/sq.ft.
528       ₹ 4,528/sq.ft.
529       ₹ 8,580/sq.ft.
530       ₹ 5,513/sq.ft.
531       ₹ 6,666/sq.ft.
532      ₹ 15,384/sq.ft.
533       ₹ 9,210/sq.ft.
534       ₹ 9,210/sq.ft.
535      ₹ 13,571/sq.ft.
536      ₹ 11,686/sq.ft.
537       ₹ 8,036/sq.ft.
538       ₹ 6,585/sq.ft.
539       ₹ 7,230/sq.ft.
540       ₹ 6,453/sq.ft.
541       ₹ 6,578/sq.ft.
542       ₹ 5,973/sq.ft.
543       ₹ 5,896/sq.ft.
544      ₹ 15,185/sq.ft.
545      ₹ 12,152/sq.ft.
546      ₹ 13,253/sq.ft.
547      ₹ 12,190/sq.ft.
548       ₹ 4,370/sq.ft.
549       ₹ 4,355/sq.ft.
550       ₹ 8,461/sq.ft.
551       ₹ 8,834/sq.ft.
552       ₹ 7,734/sq.ft.
553       ₹ 5,418/sq.ft.
554      ₹ 11,358/sq.ft.
555      ₹ 12,599/sq.ft.
556       ₹ 6,313/sq.ft.
557      ₹ 13,678/sq.ft.
558      ₹ 19,747/sq.ft.
559       ₹ 7,878/sq.ft.
560       ₹ 5,004/sq.ft.
561       ₹ 4,836/sq.ft.
562       ₹ 9,105/sq.ft.
563      ₹ 10,595/sq.ft.
564       ₹ 8,646/sq.ft.
565      ₹ 10,461/sq.ft.
566      ₹ 10,080/sq.ft.
567      ₹ 10,699/sq.ft.
568       ₹ 8,172/sq.ft.
569      ₹ 12,571/sq.ft.
570       ₹ 7,608/sq.ft.
571      ₹ 11,914/sq.ft.
572      ₹ 14,983/sq.ft.
573       ₹ 8,759/sq.ft.
574       ₹ 6,655/sq.ft.
575       ₹ 5,521/sq.ft.
576       ₹ 5,674/sq.ft.
577       ₹ 8,839/sq.ft.
578       ₹ 7,948/sq.ft.
579       ₹ 8,035/sq.ft.
580      ₹ 16,750/sq.ft.
581      ₹ 16,470/sq.ft.
582      ₹ 16,580/sq.ft.
583       ₹ 8,108/sq.ft.
584      ₹ 10,334/sq.ft.
585       ₹ 9,266/sq.ft.
586      ₹ 11,860/sq.ft.
587       ₹ 7,812/sq.ft.
588       ₹ 8,947/sq.ft.
589       ₹ 9,051/sq.ft.
590       ₹ 9,622/sq.ft.
591       ₹ 7,142/sq.ft.
592      ₹ 13,528/sq.ft.
593       ₹ 5,683/sq.ft.
594       ₹ 6,476/sq.ft.
595       ₹ 4,864/sq.ft.
596       ₹ 5,499/sq.ft.
597       ₹ 7,449/sq.ft.
598       ₹ 7,065/sq.ft.
599       ₹ 9,980/sq.ft.
600       ₹ 9,036/sq.ft.
601      ₹ 13,888/sq.ft.
602      ₹ 13,878/sq.ft.
603      ₹ 14,557/sq.ft.
604      ₹ 12,325/sq.ft.
605       ₹ 9,133/sq.ft.
606       ₹ 7,750/sq.ft.
607      ₹ 13,281/sq.ft.
608       ₹ 6,819/sq.ft.
609      ₹ 17,285/sq.ft.
610       ₹ 8,834/sq.ft.
611      ₹ 18,518/sq.ft.
612       ₹ 5,500/sq.ft.
613       ₹ 7,150/sq.ft.
614      ₹ 12,222/sq.ft.
615      ₹ 13,929/sq.ft.
616      ₹ 12,500/sq.ft.
617       ₹ 6,514/sq.ft.
618       ₹ 6,580/sq.ft.
619       ₹ 6,708/sq.ft.
620      ₹ 13,846/sq.ft.
621       ₹ 5,878/sq.ft.
622       ₹ 9,909/sq.ft.
623      ₹ 13,875/sq.ft.
624      ₹ 12,400/sq.ft.
625       ₹ 7,146/sq.ft.
626      ₹ 14,074/sq.ft.
627      ₹ 11,739/sq.ft.
628      ₹ 10,596/sq.ft.
629       ₹ 7,014/sq.ft.
630       ₹ 8,139/sq.ft.
631       ₹ 5,825/sq.ft.
632      ₹ 12,110/sq.ft.
633      ₹ 14,623/sq.ft.
634       ₹ 6,523/sq.ft.
635       ₹ 8,100/sq.ft.
636      ₹ 21,013/sq.ft.
637       ₹ 7,437/sq.ft.
638      ₹ 11,666/sq.ft.
639       ₹ 6,455/sq.ft.
640       ₹ 4,022/sq.ft.
641       ₹ 3,935/sq.ft.
642       ₹ 9,387/sq.ft.
643       ₹ 9,117/sq.ft.
644      ₹ 10,953/sq.ft.
645      ₹ 11,052/sq.ft.
646      ₹ 14,536/sq.ft.
647      ₹ 12,127/sq.ft.
648      ₹ 12,144/sq.ft.
649      ₹ 10,994/sq.ft.
650      ₹ 10,761/sq.ft.
651      ₹ 15,469/sq.ft.
652       ₹ 8,333/sq.ft.
653      ₹ 13,392/sq.ft.
654      ₹ 20,533/sq.ft.
655      ₹ 24,211/sq.ft.
656       ₹ 5,588/sq.ft.
657       ₹ 8,389/sq.ft.
658       ₹ 8,474/sq.ft.
659       ₹ 8,724/sq.ft.
660       ₹ 8,750/sq.ft.
661       ₹ 6,250/sq.ft.
662       ₹ 9,128/sq.ft.
663       ₹ 7,496/sq.ft.
664       ₹ 7,857/sq.ft.
665       ₹ 6,953/sq.ft.
666      ₹ 13,750/sq.ft.
667      ₹ 11,574/sq.ft.
668      ₹ 11,505/sq.ft.
669      ₹ 13,725/sq.ft.
670       ₹ 6,215/sq.ft.
671       ₹ 4,814/sq.ft.
672       ₹ 7,500/sq.ft.
673      ₹ 35,483/sq.ft.
674       ₹ 7,403/sq.ft.
675       ₹ 7,223/sq.ft.
676      ₹ 17,484/sq.ft.
677      ₹ 12,169/sq.ft.
678       ₹ 8,242/sq.ft.
679      ₹ 10,365/sq.ft.
680       ₹ 7,789/sq.ft.
681      ₹ 13,343/sq.ft.
682      ₹ 14,068/sq.ft.
683       ₹ 5,859/sq.ft.
684       ₹ 5,820/sq.ft.
685       ₹ 5,660/sq.ft.
686       ₹ 6,254/sq.ft.
687       ₹ 4,531/sq.ft.
688      ₹ 10,178/sq.ft.
689       ₹ 9,203/sq.ft.
690      ₹ 15,007/sq.ft.
691       ₹ 9,090/sq.ft.
692      ₹ 10,028/sq.ft.
693       ₹ 8,516/sq.ft.
694       ₹ 6,060/sq.ft.
695       ₹ 6,825/sq.ft.
696      ₹ 14,987/sq.ft.
697       ₹ 6,647/sq.ft.
698       ₹ 6,052/sq.ft.
699      ₹ 14,090/sq.ft.
700       ₹ 9,642/sq.ft.
701       ₹ 8,679/sq.ft.
702      ₹ 14,727/sq.ft.
703      ₹ 14,418/sq.ft.
704      ₹ 13,671/sq.ft.
705      ₹ 10,262/sq.ft.
706      ₹ 10,224/sq.ft.
707      ₹ 11,694/sq.ft.
708       ₹ 9,850/sq.ft.
709       ₹ 7,641/sq.ft.
710       ₹ 8,825/sq.ft.
711       ₹ 6,029/sq.ft.
712      ₹ 10,545/sq.ft.
713       ₹ 8,204/sq.ft.
714      ₹ 13,758/sq.ft.
715      ₹ 15,685/sq.ft.
716       ₹ 6,286/sq.ft.
717       ₹ 6,846/sq.ft.
718       ₹ 6,002/sq.ft.
719       ₹ 7,751/sq.ft.
720       ₹ 8,062/sq.ft.
721       ₹ 5,725/sq.ft.
722       ₹ 5,930/sq.ft.
723       ₹ 9,238/sq.ft.
724       ₹ 5,856/sq.ft.
725      ₹ 14,179/sq.ft.
726       ₹ 6,470/sq.ft.
727       ₹ 7,096/sq.ft.
728       ₹ 9,433/sq.ft.
729       ₹ 8,998/sq.ft.
730      ₹ 11,451/sq.ft.
731      ₹ 10,651/sq.ft.
732       ₹ 6,242/sq.ft.
733       ₹ 5,490/sq.ft.
734       ₹ 8,922/sq.ft.
735       ₹ 6,310/sq.ft.
736      ₹ 10,162/sq.ft.
737       ₹ 7,116/sq.ft.
738       ₹ 6,655/sq.ft.
739       ₹ 6,265/sq.ft.
740       ₹ 5,808/sq.ft.
741       ₹ 4,080/sq.ft.
742      ₹ 10,237/sq.ft.
743       ₹ 8,611/sq.ft.
744       ₹ 9,822/sq.ft.
745       ₹ 6,000/sq.ft.
746       ₹ 4,308/sq.ft.
747       ₹ 3,953/sq.ft.
748      ₹ 12,484/sq.ft.
749      ₹ 15,531/sq.ft.
750       ₹ 5,762/sq.ft.
751       ₹ 6,852/sq.ft.
752       ₹ 7,641/sq.ft.
753      ₹ 14,418/sq.ft.
754      ₹ 14,843/sq.ft.
755      ₹ 12,846/sq.ft.
756      ₹ 20,388/sq.ft.
757      ₹ 13,580/sq.ft.
758       ₹ 4,500/sq.ft.
759       ₹ 7,750/sq.ft.
760      ₹ 12,658/sq.ft.
761      ₹ 16,266/sq.ft.
762      ₹ 21,577/sq.ft.
763      ₹ 13,636/sq.ft.
764       ₹ 7,179/sq.ft.
765      ₹ 13,383/sq.ft.
766       ₹ 7,641/sq.ft.
767      ₹ 11,713/sq.ft.
768      ₹ 12,444/sq.ft.
769      ₹ 10,714/sq.ft.
770       ₹ 8,270/sq.ft.
771      ₹ 11,218/sq.ft.
772       ₹ 7,525/sq.ft.
773       ₹ 6,801/sq.ft.
774       ₹ 6,692/sq.ft.
775       ₹ 7,590/sq.ft.
776      ₹ 19,174/sq.ft.
777       ₹ 5,207/sq.ft.
778       ₹ 5,252/sq.ft.
779       ₹ 8,875/sq.ft.
780      ₹ 16,666/sq.ft.
781       ₹ 8,916/sq.ft.
782      ₹ 13,928/sq.ft.
783       ₹ 5,597/sq.ft.
784       ₹ 7,850/sq.ft.
785       ₹ 7,817/sq.ft.
786       ₹ 8,395/sq.ft.
787       ₹ 8,532/sq.ft.
788      ₹ 10,037/sq.ft.
789       ₹ 6,049/sq.ft.
790       ₹ 5,942/sq.ft.
791       ₹ 6,476/sq.ft.
792      ₹ 10,727/sq.ft.
793       ₹ 9,565/sq.ft.
794       ₹ 6,227/sq.ft.
795      ₹ 10,147/sq.ft.
796      ₹ 10,529/sq.ft.
797      ₹ 12,372/sq.ft.
798      ₹ 11,817/sq.ft.

In [115]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹' , '').str.replace(',' , '').str.strip().astype('float')

In [116]:
df['price_per_sqft'].value_counts

<bound method IndexOpsMixin.value_counts of 0         5000.0
1         7692.0
2         6722.0
3        12250.0
4         5204.0
5         6269.0
6        13333.0
7         7860.0
8         8148.0
9        16885.0
10        9767.0
11        5587.0
12        6940.0
13        6859.0
14        5384.0
15       16859.0
16       14084.0
17       11475.0
18       10476.0
19        9156.0
20        8604.0
21        7796.0
22        9135.0
23       12855.0
25        7910.0
26       18331.0
27       24300.0
28        5600.0
29       12784.0
30       26936.0
31       10156.0
32        7194.0
33        6538.0
34        5769.0
35        6950.0
36        8866.0
37        5403.0
38        5714.0
39       15151.0
40        6200.0
41       16000.0
42        6378.0
43        3571.0
44        7846.0
45        7297.0
46        7581.0
47       10005.0
48       10714.0
49       16969.0
50       14545.0
51        5424.0
52        7410.0
53        6400.0
54        4715.0
55        5000.0
56        6666.0
57        9872.0
58        6594.0
59        5555.0
60        7000.0
61        5007.0
62        7857.0
63        6376.0
64        8863.0
65        4320.0
66       11111.0
67       10410.0
68        5178.0
69        5556.0
70        4744.0
71        9406.0
72        5521.0
73        6404.0
74        8432.0
75        4687.0
76        6812.0
77       12505.0
78        5128.0
79       11153.0
80        8784.0
81          79.0
82       10599.0
83        6500.0
84        3768.0
85       17200.0
86        6338.0
87        6615.0
88        3166.0
89        9838.0
90       13957.0
91        8035.0
92        8036.0
93        8768.0
94        8611.0
95        6600.0
96       11738.0
97       14492.0
98       12800.0
99        7800.0
100      15590.0
101       5641.0
102      13750.0
103       7407.0
104      10500.0
105       9849.0
106      11482.0
107       4500.0
108      17617.0
109       6106.0
110       7739.0
111      10018.0
112      16030.0
113          7.0
114       5600.0
115       9955.0
116       9027.0
117      10589.0
118       6443.0
119       7407.0
120       6420.0
121       5405.0
122       8784.0
123      12744.0
124       9285.0
125       8000.0
126      11755.0
127      11755.0
128       7149.0
129       9146.0
130      13115.0
131       7396.0
132       5397.0
133       7909.0
134      12920.0
135       4615.0
136       7106.0
137       7692.0
138       5883.0
139       6806.0
140       9502.0
141       6200.0
142       6700.0
143       5750.0
144      12526.0
145      12244.0
146       7424.0
147      10361.0
148       6470.0
149      13600.0
150       5308.0
151       5556.0
152       4500.0
153       4666.0
154      14444.0
155       7188.0
156      10828.0
157       6111.0
158       9615.0
159      15000.0
160      15664.0
161      13496.0
162       9463.0
163       7782.0
164       7780.0
165       8043.0
166       6578.0
167       7963.0
168       6593.0
169      12185.0
170       6789.0
171       7500.0
172       7444.0
173       8108.0
174       6345.0
175       6967.0
176       6250.0
177       7627.0
178       6703.0
179       6506.0
180       6150.0
181       8928.0
182      12106.0
183      13074.0
184       8081.0
185      13136.0
186      10139.0
187       4731.0
188       5142.0
189       4258.0
190       7496.0
191      17441.0
192      12619.0
193       4546.0
194      10000.0
195       9904.0
196      15003.0
197       3970.0
198       5067.0
199      12500.0
200       4105.0
201       6667.0
202       8504.0
203      14118.0
204       8450.0
205       2700.0
206       8886.0
207      18492.0
208       7643.0
209       9166.0
210      16923.0
211       3975.0
212       4705.0
213       6225.0
214      10000.0
215       6542.0
216      18000.0
217      17990.0
218       7500.0
219      17997.0
220      18477.0
221      14168.0
222      11724.0
223       7272.0
224       7036.0
225       4105.0
226       6790.0
227       5420.0
228       6024.0
229       5882.0
230      11716.0
231      12181.0
232      12250.0
233       7455.0
234      13500.0
235       9909.0
236       9876.0
237       5000.0
238       4820.0
239       7032.0
240       5548.0
241       5888.0
242       7585.0
243       6734.0
244       9024.0
245       8000.0
246       9166.0
247      15980.0
248      10601.0
249      28000.0
250       4444.0
251      14335.0
252      15793.0
253      12500.0
254      26562.0
255       5000.0
256       6300.0
257       7777.0
258      14100.0
259       6983.0
260       5892.0
261      10158.0
262      13750.0
263       3648.0
264       7772.0
265       6739.0
266       5556.0
267       6325.0
268       6061.0
269       6429.0
270       6862.0
271       6377.0
272      10531.0
273       5038.0
274      13969.0
275       4800.0
276       5797.0
277      12000.0
278       9286.0
279       6510.0
280       5384.0
281      41245.0
282      10945.0
283       9851.0
284       8075.0
285      13269.0
286       7727.0
287      15998.0
288       7865.0
289       7400.0
290       7510.0
291       8514.0
292       4599.0
293      13000.0
294      14257.0
295       9333.0
296      14214.0
297      14110.0
298       7248.0
299       6921.0
300      10603.0
301       8620.0
302       9090.0
303       7391.0
304       4666.0
305      16960.0
306      33209.0
307      11516.0
308      14202.0
309       8181.0
310      10500.0
311       6666.0
312      11500.0
313       9900.0
314      17619.0
315      17000.0
316       8206.0
317      15240.0
318       7727.0
319      15998.0
320       7865.0
321       7400.0
322      13000.0
323      14257.0
324      14214.0
325       7248.0
326       6921.0
327      10603.0
328       8620.0
329       9090.0
330       7391.0
331       4666.0
332      16960.0
333      11516.0
334       8181.0
335       6666.0
336       9900.0
337      17619.0
338       8206.0
339      19363.0
340       5832.0
341       9777.0
342       6542.0
343       8160.0
344       9334.0
345       9473.0
346       6597.0
347       5897.0
348      18181.0
349       4271.0
350       7725.0
351      10895.0
352      11845.0
353      23401.0
354       9182.0
355      12782.0
356      15681.0
357       7539.0
358       8072.0
359      14376.0
360       9221.0
361       8606.0
362      10000.0
363      14516.0
364      14583.0
365      19200.0
366       8047.0
367       4888.0
368      10007.0
369      13765.0
370      14478.0
371       4651.0
372       9740.0
373       9552.0
374      14800.0
375      18571.0
376      14500.0
377       8604.0
378       8521.0
379       6509.0
380      11028.0
381       6134.0
382      11426.0
383      11938.0
384      13281.0
385      12318.0
386       8510.0
387      12810.0
388       7825.0
389       7825.0
390      14938.0
391       6709.0
392      10769.0
393       8087.0
394       8181.0
395      10378.0
396      13696.0
397       8043.0
398      10000.0
399       7267.0
400      11832.0
401      14254.0
402      11903.0
403      13224.0
404      12000.0
405      13636.0
406      14242.0
407       5681.0
408       4881.0
409       4259.0
410      11185.0
411      15575.0
412       7804.0
413       9895.0
414       7884.0
415      17455.0
416      17777.0
417       7272.0
418      13383.0
419      12312.0
420      11584.0
421       5011.0
422      13266.0
423      11505.0
424       7600.0
425      15384.0
426       9490.0
427       9558.0
428      28266.0
429      13750.0
430       7869.0
431      13495.0
432      18400.0
433       8484.0
434      17721.0
435       5530.0
436      16060.0
437      12346.0
438       7674.0
439       6921.0
440      14871.0
441       9473.0
442      11121.0
443      14242.0
444      16486.0
445       8410.0
446      16969.0
447      21360.0
448      14583.0
449      26790.0
450      12500.0
451      10516.0
452      10936.0
453       7945.0
454       7220.0
455      12627.0
456       7392.0
457       6049.0
458      12818.0
459      16050.0
460      18500.0
461       5505.0
462       7541.0
463       9000.0
464       7541.0
465       6679.0
466       6597.0
467      13125.0
468       5788.0
469      13690.0
470       8051.0
471       6141.0
472      28101.0
473       8080.0
474       7260.0
475       8376.0
476      14950.0
477       9783.0
478      12544.0
479       7150.0
480      12235.0
481      14418.0
482      14079.0
483       6713.0
484      13790.0
485      10814.0
486      12140.0
487      15160.0
488       7610.0
489       6661.0
490       7780.0
491       6163.0
492       7350.0
493      10901.0
494       8163.0
495       6000.0
496       4193.0
497       3309.0
498      15906.0
499      11294.0
500      11204.0
501       8484.0
502      11470.0
503      10567.0
504      10000.0
505      12788.0
506      13076.0
507       6987.0
508       6826.0
509       9528.0
510      15514.0
511      14563.0
512       9212.0
513       6888.0
514      11412.0
515      11174.0
516      10841.0
517       4857.0
518      10936.0
519       5717.0
520      10000.0
521       5867.0
522      14177.0
523      10174.0
524       7646.0
525       6961.0
526       8632.0
527       7586.0
528       4528.0
529       8580.0
530       5513.0
531       6666.0
532      15384.0
533       9210.0
534       9210.0
535      13571.0
536      11686.0
537       8036.0
538       6585.0
539       7230.0
540       6453.0
541       6578.0
542       5973.0
543       5896.0
544      15185.0
545      12152.0
546      13253.0
547      12190.0
548       4370.0
549       4355.0
550       8461.0
551       8834.0
552       7734.0
553       5418.0
554      11358.0
555      12599.0
556       6313.0
557      13678.0
558      19747.0
559       7878.0
560       5004.0
561       4836.0
562       9105.0
563      10595.0
564       8646.0
565      10461.0
566      10080.0
567      10699.0
568       8172.0
569      12571.0
570       7608.0
571      11914.0
572      14983.0
573       8759.0
574       6655.0
575       5521.0
576       5674.0
577       8839.0
578       7948.0
579       8035.0
580      16750.0
581      16470.0
582      16580.0
583       8108.0
584      10334.0
585       9266.0
586      11860.0
587       7812.0
588       8947.0
589       9051.0
590       9622.0
591       7142.0
592      13528.0
593       5683.0
594       6476.0
595       4864.0
596       5499.0
597       7449.0
598       7065.0
599       9980.0
600       9036.0
601      13888.0
602      13878.0
603      14557.0
604      12325.0
605       9133.0
606       7750.0
607      13281.0
608       6819.0
609      17285.0
610       8834.0
611      18518.0
612       5500.0
613       7150.0
614      12222.0
615      13929.0
616      12500.0
617       6514.0
618       6580.0
619       6708.0
620      13846.0
621       5878.0
622       9909.0
623      13875.0
624      12400.0
625       7146.0
626      14074.0
627      11739.0
628      10596.0
629       7014.0
630       8139.0
631       5825.0
632      12110.0
633      14623.0
634       6523.0
635       8100.0
636      21013.0
637       7437.0
638      11666.0
639       6455.0
640       4022.0
641       3935.0
642       9387.0
643       9117.0
644      10953.0
645      11052.0
646      14536.0
647      12127.0
648      12144.0
649      10994.0
650      10761.0
651      15469.0
652       8333.0
653      13392.0
654      20533.0
655      24211.0
656       5588.0
657       8389.0
658       8474.0
659       8724.0
660       8750.0
661       6250.0
662       9128.0
663       7496.0
664       7857.0
665       6953.0
666      13750.0
667      11574.0
668      11505.0
669      13725.0
670       6215.0
671       4814.0
672       7500.0
673      35483.0
674       7403.0
675       7223.0
676      17484.0
677      12169.0
678       8242.0
679      10365.0
680       7789.0
681      13343.0
682      14068.0
683       5859.0
684       5820.0
685       5660.0
686       6254.0
687       4531.0
688      10178.0
689       9203.0
690      15007.0
691       9090.0
692      10028.0
693       8516.0
694       6060.0
695       6825.0
696      14987.0
697       6647.0
698       6052.0
699      14090.0
700       9642.0
701       8679.0
702      14727.0
703      14418.0
704      13671.0
705      10262.0
706      10224.0
707      11694.0
708       9850.0
709       7641.0
710       8825.0
711       6029.0
712      10545.0
713       8204.0
714      13758.0
715      15685.0
716       6286.0
717       6846.0
718       6002.0
719       7751.0
720       8062.0
721       5725.0
722       5930.0
723       9238.0
724       5856.0
725      14179.0
726       6470.0
727       7096.0
728       9433.0
729       8998.0
730      11451.0
731      10651.0
732       6242.0
733       5490.0
734       8922.0
735       6310.0
736      10162.0
737       7116.0
738       6655.0
739       6265.0
740       5808.0
741       4080.0
742      10237.0
743       8611.0
744       9822.0
745       6000.0
746       4308.0
747       3953.0
748      12484.0
749      15531.0
750       5762.0
751       6852.0
752       7641.0
753      14418.0
754      14843.0
755      12846.0
756      20388.0
757      13580.0
758       4500.0
759       7750.0
760      12658.0
761      16266.0
762      21577.0
763      13636.0
764       7179.0
765      13383.0
766       7641.0
767      11713.0
768      12444.0
769      10714.0
770       8270.0
771      11218.0
772       7525.0
773       6801.0
774       6692.0
775       7590.0
776      19174.0
777       5207.0
778       5252.0
779       8875.0
780      16666.0
781       8916.0
782      13928.0
783       5597.0
784       7850.0
785       7817.0
786       8395.0
787       8532.0
788      10037.0
789       6049.0
790       5942.0
791       6476.0
792      10727.0
793       9565.0
794       6227.0
795      10147.0
796      10529.0
797      12372.0
798      11817.0
799      15454.0
800       6530.0
801       6571.0
802      15561.0
803      13352.0
804       6774.0
805       8793.0
806       6625.0
807      10443.0
808      10786.0
809       9139.0
810       9627.0
811      10041.0
812       9011.0
813      11727.0
814      10489.0
815      15195.0
816      14478.0
817       5929.0
818       9365.0
819       8704.0
820       8000.0
821       6542.0
822       8623.0
823       9039.0
824       8283.0
825       8411.0
826       9950.0
827       8886.0
828      12047.0
829      10553.0
830       9742.0
831       7072.0
832       7180.0
833      18126.0
834       7380.0
835       9512.0
836       8708.0
837       7954.0
838       8023.0
839      13636.0
840      11412.0
841       9052.0
842       4746.0
843       8400.0
844       9497.0
845      10954.0
846       6104.0
847       6019.0
848       5531.0
849       5744.0
850      10853.0
851       8294.0
852      12589.0
853       3477.0
854       7954.0
855      10799.0
856      10638.0
857       9169.0
858       9655.0
859       8814.0
860      11489.0
861       8031.0
862       6424.0
863       9030.0
864       9550.0
865       8571.0
866       7443.0
867       7208.0
868       8553.0
869      16129.0
870      11764.0
871      12813.0
872       8237.0
873       9584.0
874       6538.0
875       8484.0
876      14615.0
877      12178.0
878       7954.0
879       6932.0
880       7196.0
881       9972.0
882      15418.0
883       7750.0
884       9074.0
885       8541.0
886       6086.0
887       8000.0
888       9182.0
889      10645.0
890      13589.0
891       9563.0
892      10465.0
893      13076.0
894       7765.0
895       7250.0
896       8813.0
897       9393.0
898       8450.0
899       7948.0
900       8461.0
901       6402.0
902       9020.0
903       7928.0
904       7636.0
905       5026.0
906       5641.0
907       8256.0
908       6851.0
909      10755.0
910       6774.0
911      11438.0
912       8320.0
913       7167.0
914      12134.0
915       7339.0
916       8283.0
917       6024.0
918       7223.0
919       6641.0
920      10416.0
921      11233.0
922       7554.0
923       8818.0
924       7297.0
925       6609.0
926       5607.0
927       5422.0
928      16959.0
929      14375.0
930       3152.0
931       6421.0
932       5856.0
933       8412.0
934      14242.0
935       8835.0
936       7991.0
937       5887.0
938       6455.0
939       4761.0
940       6465.0
941       6975.0
942      11227.0
943       8163.0
944      14598.0
945      11000.0
946       7250.0
947       7250.0
948       8536.0
949      19000.0
950      18000.0
951      15510.0
952      24963.0
953       4961.0
954       8139.0
955       8324.0
956       8484.0
957      10601.0
958       9933.0
959       9011.0
960       7652.0
961      14040.0
962       6369.0
963      10825.0
964      11050.0
965      14285.0
966      10449.0
967       6353.0
968       6353.0
969       7272.0
970       9550.0
971       5605.0
972       6406.0
973       7150.0
974       5808.0
975      12533.0
976      11338.0
977       6839.0
978       7716.0
979       5982.0
980       8389.0
981      12732.0
982      11868.0
983       8769.0
984      12371.0
985      13318.0
986      12471.0
987      11966.0
988      13837.0
989       8139.0
990       6267.0
991       5747.0
992       7904.0
993       9473.0
994       8648.0
995       8539.0
996       8024.0
997       8458.0
998      11628.0
999       6459.0
1000      7407.0
1001      6679.0
1002      7258.0
1003      6653.0
1004      6896.0
1005      7268.0
1006     12567.0
1007      8461.0
1008      6330.0
1009      6649.0
1010      6153.0
1011      9306.0
1012     11727.0
1013     13235.0
1014      8139.0
1015      6079.0
1016     12622.0
1017      8000.0
1018     19285.0
1019     16000.0
1020      6934.0
1021     15648.0
1022     11363.0
1023     11111.0
1024     16363.0
1025     10323.0
1026     11956.0
1027     13709.0
1028     13709.0
1029     13915.0
1030      8457.0
1031     17391.0
1032      5513.0
1033      7090.0
1034      5454.0
1035      8424.0
1036     10364.0
1037      7987.0
1038      7074.0
1039      7302.0
1040      8000.0
1041      9350.0
1042      5960.0
1043     14991.0
1044     26086.0
1045     10250.0
1046     10638.0
1047      6382.0
1048      5699.0
1049      8967.0
1050      8410.0
1051     14683.0
1052     14303.0
1053     30180.0
1054      6313.0
1055      4717.0
1056     12802.0
1057      5177.0
1058      7179.0
1059      8179.0
1060      8305.0
1061      6224.0
1062     12401.0
1063     20602.0
1064     14430.0
1065     13636.0
1066     14242.0
1067     16969.0
1068     16206.0
1069     13924.0
1070     14303.0
1071     14107.0
1072      5961.0
1073     11000.0
1074      9589.0
1075     10685.0
1076      7000.0
1077     10479.0
1078      7496.0
1079      5564.0
1080      9590.0
1081     11401.0
1082      8955.0
1083      8855.0
1084      9632.0
1085      9822.0
1086      8031.0
1087      8547.0
1088     11162.0
1089      8753.0
1090     11770.0
1091      6387.0
1092      5833.0
1093      5000.0
1094      5014.0
1095     14615.0
1096      6003.0
1097      6442.0
1098      9305.0
1099     12815.0
1100     14018.0
1101     11363.0
1102     11767.0
1103      6567.0
1104      6192.0
1105     12444.0
1106      6412.0
1107      6533.0
1108      5932.0
1109      5979.0
1110      5221.0
1111      9046.0
1112      4857.0
1113      6789.0
1114      5771.0
1115      4951.0
1116      6746.0
1117      7350.0
1118      8348.0
1119      8408.0
1120      8861.0
1121     10928.0
1122      6243.0
1123      4237.0
1124      5305.0
1125     15189.0
1126      6837.0
1127     10545.0
1128      6143.0
1129      6184.0
1130      7317.0
1131      7645.0
1132      8730.0
1133      8841.0
1134      8883.0
1135      8882.0
1136      8966.0
1137      8227.0
1138      8675.0
1139      8411.0
1140      8445.0
1141      6735.0
1142      7776.0
1143      8358.0
1144      8871.0
1145      7894.0
1146      7751.0
1147      5980.0
1148      6692.0
1149      5644.0
1150      5354.0
1151      8214.0
1152      7500.0
1153     11666.0
1154      5828.0
1155      5674.0
1156      5623.0
1157      5725.0
1158      6527.0
1159      6489.0
1160      7906.0
1161      6398.0
1162      5828.0
1163      6581.0
1164     12121.0
1165      9768.0
1166     16233.0
1167      8706.0
1168      4854.0
1169      4906.0
1170      5252.0
1171     12863.0
1172      8000.0
1173      8333.0

In [118]:
df['areaWithType'].value_counts

<bound method IndexOpsMixin.value_counts of 0                          Carpet area: 900 (83.61 sq.m.)
1                          Carpet area: 650 (60.39 sq.m.)
2                          Carpet area: 595 (55.28 sq.m.)
3                        Carpet area: 1200 (111.48 sq.m.)
4                  Super Built up area 1345(124.95 sq.m.)
5                        Built Up area: 654 (60.76 sq.m.)
6                  Super Built up area 1500(139.35 sq.m.)
7                        Carpet area: 2290 (212.75 sq.m.)
8       Built Up area: 1350 (125.42 sq.m.)Carpet area:...
9                      Built Up area: 2813 (261.34 sq.m.)
10                        Carpet area: 1075 (99.87 sq.m.)
11                         Carpet area: 519 (48.22 sq.m.)
12                        Carpet area: 1945 (180.7 sq.m.)
13                 Super Built up area 1385(128.67 sq.m.)
14                 Super Built up area 1300(120.77 sq.m.)
15      Built Up area: 2343 (217.67 sq.m.)Carpet area:...
16                       Built Up area: 639 (59.37 sq.m.)
17                         Carpet area: 915 (85.01 sq.m.)
18                  Super Built up area 2100(195.1 sq.m.)
19                       Carpet area: 1103 (102.47 sq.m.)
20                 Super Built up area 2150(199.74 sq.m.)
21                 Super Built up area 1103(102.47 sq.m.)
22                       Carpet area: 2025 (188.13 sq.m.)
23                 Super Built up area 2217(205.97 sq.m.)
25                         Carpet area: 531 (49.33 sq.m.)
26      Built Up area: 3355 (311.69 sq.m.)Carpet area:...
27                       Carpet area: 2880 (267.56 sq.m.)
28                         Carpet area: 750 (69.68 sq.m.)
29      Built Up area: 1056 (98.11 sq.m.)Carpet area: ...
30                          Carpet area: 66 (55.18 sq.m.)
31      Super Built up area 3200(297.29 sq.m.)Carpet a...
32                      Carpet area: 625.47 (58.11 sq.m.)
33                     Built Up area: 1300 (120.77 sq.m.)
34                       Carpet area: 1300 (120.77 sq.m.)
35                 Super Built up area 1180(109.63 sq.m.)
36      Super Built up area 2030(188.59 sq.m.)Carpet a...
37      Super Built up area 655(60.85 sq.m.)Carpet are...
38      Super Built up area 1365(126.81 sq.m.)Built Up...
39                       Carpet area: 1320 (122.63 sq.m.)
40                       Carpet area: 1210 (112.41 sq.m.)
41                       Carpet area: 2002 (185.99 sq.m.)
42                 Super Built up area 1960(182.09 sq.m.)
43                         Carpet area: 700 (65.03 sq.m.)
44      Built Up area: 1210.73 (112.48 sq.m.)Carpet ar...
45                       Carpet area: 2727 (253.35 sq.m.)
46                       Carpet area: 1385 (128.67 sq.m.)
47                       Carpet area: 1829 (169.92 sq.m.)
48                        Carpet area: 2100 (195.1 sq.m.)
49                       Carpet area: 1650 (153.29 sq.m.)
50                       Carpet area: 1100 (102.19 sq.m.)
51                       Carpet area: 1530 (142.14 sq.m.)
52                       Carpet area: 1120 (104.05 sq.m.)
53                       Carpet area: 1250 (116.13 sq.m.)
54                       Carpet area: 2651 (246.29 sq.m.)
55                         Carpet area: 460 (42.74 sq.m.)
56                         Carpet area: 450 (41.81 sq.m.)
57                 Super Built up area 1570(145.86 sq.m.)
58                  Super Built up area 1198(111.3 sq.m.)
59      Super Built up area 900(83.61 sq.m.)Carpet are...
60      Super Built up area 1450(134.71 sq.m.)Carpet a...
61                 Super Built up area 1897(176.24 sq.m.)
62      Super Built up area 1260(117.06 sq.m.)Carpet a...
63                 Super Built up area 1725(160.26 sq.m.)
64                 Super Built up area 2200(204.39 sq.m.)
65                 Super Built up area 1875(174.19 sq.m.)
66                 Super Built up area 2250(209.03 sq.m.)
67               Super Built up area 1056.58(98.16 sq.m.)
68                   Super Built up area 560(52.03 sq.m.)
69      Built Up area: 990 (91.97 sq.m.)Carpet area: 9...
70                 Super Built up area 1370(127.28 sq.m.)
71                      Carpet area: 531.57 (49.38 sq.m.)
72      Super Built up area 575(53.42 sq.m.)Carpet are...
73                        Carpet area: 1452 (134.9 sq.m.)
74                        Carpet area: 1423 (132.2 sq.m.)
75                         Carpet area: 640 (59.46 sq.m.)
76                         Carpet area: 822 (76.37 sq.m.)
77                 Super Built up area 2159(200.58 sq.m.)
78                 Super Built up area 1950(181.16 sq.m.)
79      Built Up area: 1300 (120.77 sq.m.)Carpet area:...
80      Built Up area: 1423 (132.2 sq.m.)Carpet area: ...
81                     Carpet area: 58141 (5401.48 sq.m.)
82                 Super Built up area 3670(340.95 sq.m.)
83                   Super Built up area 1000(92.9 sq.m.)
84      Built Up area: 743 (69.03 sq.m.)Carpet area: 6...
85      Super Built up area 2250(209.03 sq.m.)Carpet a...
86                       Carpet area: 2177 (202.25 sq.m.)
87                         Carpet area: 650 (60.39 sq.m.)
88                         Carpet area: 900 (83.61 sq.m.)
89                       Carpet area: 1118 (103.87 sq.m.)
90      Built Up area: 1433 (133.13 sq.m.)Carpet area:...
91                 Super Built up area 1120(104.05 sq.m.)
92                     Built Up area: 1120 (104.05 sq.m.)
93                     Built Up area: 1996 (185.43 sq.m.)
94                       Carpet area: 1080 (100.34 sq.m.)
95                 Super Built up area 2727(253.35 sq.m.)
96                  Super Built up area 1789(166.2 sq.m.)
97                       Carpet area: 1380 (128.21 sq.m.)
98                     Built Up area: 1540 (143.07 sq.m.)
99      Super Built up area 1629(151.34 sq.m.)Carpet a...
100                Super Built up area 1828(169.83 sq.m.)
101                      Carpet area: 1950 (181.16 sq.m.)
102                      Carpet area: 1200 (111.48 sq.m.)
103                         Carpet area: 324 (30.1 sq.m.)
104     Super Built up area 2000(185.81 sq.m.)Built Up...
105                      Carpet area: 1929 (179.21 sq.m.)
106                                Super Built up area 89
107     Super Built up area 700(65.03 sq.m.)Carpet are...
108     Built Up area: 965 (89.65 sq.m.)Carpet area: 6...
109     Super Built up area 524(48.68 sq.m.)Carpet are...
110                     Carpet area: 581.41 (54.01 sq.m.)
111     Super Built up area 1197.8(111.28 sq.m.)Carpet...
112                 Super Built up area 1310(121.7 sq.m.)
113                  Carpet area: 569243 (52884.41 sq.m.)
114                        Carpet area: 750 (69.68 sq.m.)
115                      Carpet area: 1557 (144.65 sq.m.)
116                Super Built up area 1440(133.78 sq.m.)
117                      Carpet area: 2597 (241.27 sq.m.)
118     Super Built up area 1940(180.23 sq.m.)Carpet a...
119                        Carpet area: 567 (52.68 sq.m.)
120     Super Built up area 623(57.88 sq.m.)Carpet are...
121                        Carpet area: 629 (58.44 sq.m.)
122                 Super Built up area 1423(132.2 sq.m.)
123     Super Built up area 1450(134.71 sq.m.)Carpet a...
124                Super Built up area 1400(130.06 sq.m.)
125                Super Built up area 2000(185.81 sq.m.)
126                      Carpet area: 1276 (118.54 sq.m.)
127                Super Built up area 1276(118.54 sq.m.)
128                    Built Up area: 1259 (116.96 sq.m.)
129                Super Built up area 1640(152.36 sq.m.)
130                      Built Up area: 610 (56.67 sq.m.)
131                Super Built up area 1690(157.01 sq.m.)
132                     Carpet area: 481.74 (44.76 sq.m.)
133                        Carpet area: 531 (49.33 sq.m.)
134                 Super Built up area 215(179.77 sq.m.)
135     Super Built up area 1950(181.16 sq.m.)Built Up...
136                        Carpet area: 591 (54.91 sq.m.)
137                  Super Built up area 546(50.73 sq.m.)
138     Super Built up area 1530(142.14 sq.m.)Built Up...
139                      Carpet area: 1910 (177.44 sq.m.)
140                 Super Built up area 1789(166.2 sq.m.)
141                    Built Up area: 2040 (189.52 sq.m.)
142     Super Built up area 4350(404.13 sq.m.)Carpet a...
143     Super Built up area 2500(232.26 sq.m.)Built Up...
144                           Carpet area: 958 (89 sq.m.)
145                      Carpet area: 1225 (113.81 sq.m.)
146     Super Built up area 1751(162.67 sq.m.)Carpet a...
147                Super Built up area 1689(156.91 sq.m.)
148                        Carpet area: 700 (65.03 sq.m.)
149                Super Built up area 1828(169.83 sq.m.)
150                  Super Built up area 810(75.25 sq.m.)
151     Built Up area: 1440 (133.78 sq.m.)Carpet area:...
152                  Super Built up area 1000(92.9 sq.m.)
153     Built Up area: 1468 (136.38 sq.m.)Carpet area:...
154     Super Built up area 2191(203.55 sq.m.)Built Up...
155                        Carpet area: 626 (58.16 sq.m.)
156     Built Up area: 1570 (145.86 sq.m.)Carpet area:...
157                      Carpet area: 1800 (167.23 sq.m.)
158                        Carpet area: 520 (48.31 sq.m.)
159                Super Built up area 1828(169.83 sq.m.)
160              Built Up area: 118 Carpet area: 86 sq.m.
161                      Carpet area: 1630 (151.43 sq.m.)
162     Super Built up area 1275(118.45 sq.m.)Carpet a...
163                        Carpet area: 514 (47.75 sq.m.)
164     Super Built up area 1735(161.19 sq.m.)Carpet a...
165                      Carpet area: 2300 (213.68 sq.m.)
166                   Super Built up area 380(35.3 sq.m.)
167                      Carpet area: 1105 (102.66 sq.m.)
168                Super Built up area 1365(126.81 sq.m.)
169                Super Built up area 1313(121.98 sq.m.)
170                Super Built up area 1252(116.31 sq.m.)
171     Built Up area: 1000 (92.9 sq.m.)Carpet area: 6...
172                      Carpet area: 4500 (418.06 sq.m.)
173                Super Built up area 1850(171.87 sq.m.)
174                Super Built up area 2364(219.62 sq.m.)
175                Super Built up area 2727(253.35 sq.m.)
176                      Carpet area: 2800 (260.13 sq.m.)
177                      Carpet area: 1180 (109.63 sq.m.)
178                Super Built up area 1865(173.26 sq.m.)
179                      Carpet area: 1537 (142.79 sq.m.)
180                    Built Up area: 1758 (163.32 sq.m.)
181                Super Built up area 2408(223.71 sq.m.)
182                      Built Up area: 826 (76.74 sq.m.)
183                Super Built up area 1262(117.24 sq.m.)
184                      Carpet area: 2215 (205.78 sq.m.)
185                                    Carpet area: 127.3
186     Built Up area: 1430 (132.85 sq.m.)Carpet area:...
187     Super Built up area 585(54.35 sq.m.)Carpet are...
188                      Built Up area: 700 (65.03 sq.m.)
189                      Built Up area: 587 (54.53 sq.m.)
190     Super Built up area 1534(142.51 sq.m.)Built Up...
191                        Carpet area: 946 (87.89 sq.m.)
192                      Carpet area: 2298 (213.49 sq.m.)
193                Super Built up area 1320(122.63 sq.m.)
194                      Carpet area: 2400 (222.97 sq.m.)
195                      Carpet area: 1262 (117.24 sq.m.)
196                    Built Up area: 1433 (133.13 sq.m.)
197     Built Up area: 743 (69.03 sq.m.)Carpet area: 5...
198     Built Up area: 750 (69.68 sq.m.)Carpet area: 6...
199     Built Up area: 1200 (111.48 sq.m.)Carpet area:...
200     Built Up area: 950 (88.26 sq.m.)Carpet area: 7...
201                    Built Up area: 2400 (222.97 sq.m.)
202                Super Built up area 1999(185.71 sq.m.)
203                      Carpet area: 2302 (213.86 sq.m.)
204                        Carpet area: 710 (65.96 sq.m.)
205     Super Built up area 1000(92.9 sq.m.)Carpet are...
206                       Carpet area: 1069 (99.31 sq.m.)
207                Super Built up area 1433(133.13 sq.m.)
208     Built Up area: 546 (50.73 sq.m.)Carpet area: 4...
209                  Super Built up area 600(55.74 sq.m.)
210                        Carpet area: 780 (72.46 sq.m.)
211             Super Built up area 1252.13(116.33 sq.m.)
212                        Carpet area: 850 (78.97 sq.m.)
213     Super Built up area 1285(119.38 sq.m.)Built Up...
214                      Carpet area: 1400 (130.06 sq.m.)
215     Super Built up area 1452(134.9 sq.m.)Carpet ar...
216                Super Built up area 1828(169.83 sq.m.)
217                Super Built up area 2040(189.52 sq.m.)
218                      Carpet area: 5140 (477.52 sq.m.)
219                Super Built up area 1828(169.83 sq.m.)
220                Super Built up area 1261(117.15 sq.m.)
221                Super Built up area 1828(169.83 sq.m.)
222                    Built Up area: 2900 (269.42 sq.m.)
223                        Carpet area: 990 (91.97 sq.m.)
224               Super Built up area 568.46(52.81 sq.m.)
225                Super Built up area 1364(126.72 sq.m.)
226                 Super Built up area 1620(150.5 sq.m.)
227     Super Built up area 1310(121.7 sq.m.)Built Up ...
228                Super Built up area 1295(120.31 sq.m.)
229                        Carpet area: 680 (63.17 sq.m.)
230                Super Built up area 1579(146.69 sq.m.)
231                  Super Built up area 903(83.89 sq.m.)
232                    Built Up area: 1150 (106.84 sq.m.)
233                       Carpet area: 1945 (180.7 sq.m.)
234                      Carpet area: 1600 (148.64 sq.m.)
235     Super Built up area 1110(103.12 sq.m.)Built Up...
236                      Carpet area: 2025 (188.13 sq.m.)
237                      Carpet area: 1200 (111.48 sq.m.)
238                Super Built up area 1660(154.22 sq.m.)
239     Super Built up area 583(54.16 sq.m.)Built Up a...
240                    Built Up area: 1622 (150.69 sq.m.)
241                        Carpet area: 900 (83.61 sq.m.)
242     Super Built up area 1081(100.43 sq.m.)Carpet a...
243                Super Built up area 1485(137.96 sq.m.)
244                      Carpet area: 2050 (190.45 sq.m.)
245                       Carpet area: 1775 (164.9 sq.m.)
246     Super Built up area 850(78.97 sq.m.)Built Up a...
247                      Carpet area: 1433 (133.13 sq.m.)
248     Super Built up area 915(85.01 sq.m.)Carpet are...
249                Super Built up area 2940(273.13 sq.m.)
250                        Carpet area: 675 (62.71 sq.m.)
251                      Carpet area: 1151 (106.93 sq.m.)
252                Super Built up area 1260(117.06 sq.m.)
253                        Carpet area: 800 (74.32 sq.m.)
254                      Carpet area: 1600 (148.64 sq.m.)
255     Super Built up area 2350(218.32 sq.m.)Built Up...
256                      Carpet area: 1340 (124.49 sq.m.)
257                      Carpet area: 1350 (125.42 sq.m.)
258                Super Built up area 2905(269.88 sq.m.)
259                        Carpet area: 716 (66.52 sq.m.)
260                      Carpet area: 2800 (260.13 sq.m.)
261                      Carpet area: 1575 (146.32 sq.m.)
262     Super Built up area 1549(143.91 sq.m.)Carpet a...
263                Super Built up area 2467(229.19 sq.m.)
264                Super Built up area 1351(125.51 sq.m.)
265                Super Built up area 1365(126.81 sq.m.)
266                     Built Up area: 140 (117.06 sq.m.)
267                Super Built up area 1565(145.39 sq.m.)
268     Super Built up area 1295(120.31 sq.m.)Carpet a...
269                Super Built up area 1361(126.44 sq.m.)
270                      Carpet area: 1326 (123.19 sq.m.)
271                Super Built up area 1960(182.09 sq.m.)
272                        Carpet area: 997 (92.62 sq.m.)
273                     Built Up area: 1310 (121.7 sq.m.)
274                     Built Up area: 1310 (121.7 sq.m.)
275                Super Built up area 1095(101.73 sq.m.)
276     Super Built up area 1380(128.21 sq.m.)Built Up...
277                     Built Up area: 1423 (132.2 sq.m.)
278                      Built Up area: 700 (65.03 sq.m.)
279                    Built Up area: 1997 (185.53 sq.m.)
280                    Built Up area: 1523 (141.49 sq.m.)
281                    Built Up area: 1382 (128.39 sq.m.)
282     Built Up area: 804 (74.69 sq.m.)Carpet area: 6...
283                    Built Up area: 3350 (311.23 sq.m.)
284     Super Built up area 2408(223.71 sq.m.)Built Up...
285                Super Built up area 2600(241.55 sq.m.)
286     Built Up area: 2200 (204.39 sq.m.)Carpet area:...
287                      Carpet area: 3844 (357.12 sq.m.)
288                Super Built up area 1780(165.37 sq.m.)
289     Super Built up area 2000(185.81 sq.m.)Carpet a...
290                      Carpet area: 4328 (402.08 sq.m.)
291                      Carpet area: 1750 (162.58 sq.m.)
292                         Carpet area: 761 (70.7 sq.m.)
293                       Carpet area: 2452 (227.8 sq.m.)
294                       Carpet area: 1508 (140.1 sq.m.)
295     Super Built up area 1500(139.35 sq.m.)Carpet a...
296                Super Built up area 1407(130.71 sq.m.)
297                Super Built up area 1630(151.43 sq.m.)
298                        Carpet area: 745 (69.21 sq.m.)
299                      Carpet area: 1806 (167.78 sq.m.)
300               Built Up area: 97 Carpet area: 92 sq.m.
301                      Carpet area: 1450 (134.71 sq.m.)
302                Super Built up area 1100(102.19 sq.m.)
303                      Carpet area: 2300 (213.68 sq.m.)
304                Super Built up area 2786(258.83 sq.m.)
305     Built Up area: 1852 (172.06 sq.m.)Carpet area:...
306                    Carpet area: 1249.65 (116.1 sq.m.)
307                Super Built up area 2605(242.01 sq.m.)
308                      Carpet area: 1549 (143.91 sq.m.)
309     Super Built up area 1650(153.29 sq.m.)Carpet a...
310                      Carpet area: 1671 (155.24 sq.m.)
311                Super Built up area 1350(125.42 sq.m.)
312     Built Up area: 2060 (191.38 sq.m.)Carpet area:...
313                      Carpet area: 2000 (185.81 sq.m.)
314                       Carpet area: 2100 (195.1 sq.m.)
315                      Carpet area: 2750 (255.48 sq.m.)
316                Super Built up area 1572(146.04 sq.m.)
317     Super Built up area 1870(173.73 sq.m.)Built Up...
318     Built Up area: 2200 (204.39 sq.m.)Carpet area:...
319                      Carpet area: 3844 (357.12 sq.m.)
320                Super Built up area 1780(165.37 sq.m.)
321     Super Built up area 2000(185.81 sq.m.)Carpet a...
322                       Carpet area: 2452 (227.8 sq.m.)
323                       Carpet area: 1508 (140.1 sq.m.)
324                Super Built up area 1407(130.71 sq.m.)
325                        Carpet area: 745 (69.21 sq.m.)
326                      Carpet area: 1806 (167.78 sq.m.)
327               Built Up area: 97 Carpet area: 92 sq.m.
328                      Carpet area: 1450 (134.71 sq.m.)
329                Super Built up area 1100(102.19 sq.m.)
330                      Carpet area: 2300 (213.68 sq.m.)
331                Super Built up area 2786(258.83 sq.m.)
332     Built Up area: 1852 (172.06 sq.m.)Carpet area:...
333                Super Built up area 2605(242.01 sq.m.)
334     Super Built up area 1650(153.29 sq.m.)Carpet a...
335                Super Built up area 1350(125.42 sq.m.)
336                      Carpet area: 2000 (185.81 sq.m.)
337                       Carpet area: 2100 (195.1 sq.m.)
338                Super Built up area 1572(146.04 sq.m.)
339                Super Built up area 2892(268.68 sq.m.)
340                Super Built up area 2143(199.09 sq.m.)
341                      Carpet area: 1304 (121.15 sq.m.)
342     Super Built up area 1758(163.32 sq.m.)Carpet a...
343     Built Up area: 1250 (116.13 sq.m.)Carpet area:...
344                Super Built up area 4553(422.99 sq.m.)

In [120]:
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     943
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [124]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [125]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [126]:
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1043
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [131]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [132]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [133]:
df['balcony'].value_counts()

balcony
3 Balconies     973
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [135]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No' , '0')

In [136]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [137]:
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Study Room,Pooja Room                              8
Servant Room,Study Room                            8
Study Room,Servant Room,Store Room                 7
Pooja Room,Store Room                              6
Pooja Room,Others                                  6
Others,Servant Room                                6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Servant Room,Others                     6
Study Room,Servant Room,Others                     5
Pooja Room,Store Room,Study Room,Servant Room      4
Pooja Room,Study Room,Store Room                   4
Servant Room,Pooja Room,Study Room,Store Room      3
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Study Room,Store Room                 2
Pooja Room,Study Room,Others                       2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Store Room,Pooja Room,Servant Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Pooja Room,Servant Room,Study Room,Store Room      1
Pooja Room,Study Room,Store Room,Servant Room      1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [140]:
df['additionalRoom'].isnull().sum()

0

In [139]:
df['additionalRoom'].fillna('not available' , inplace = True)

C:\Users\virat\AppData\Local\Temp\ipykernel_7972\196059762.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['additionalRoom'].fillna('not available' , inplace = True)

In [141]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [142]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [143]:
df['floorNum'].isnull().sum()

2

In [144]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
180,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2765,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [145]:
df['floorNum'].value_counts()

floorNum
2nd   of 4 Floors           74
3rd   of 4 Floors           71
4th   of 4 Floors           62
1st   of 4 Floors           61
12nd   of 14 Floors         49
14th   of 14 Floors         48
Ground of 14 Floors         40
10th   of 14 Floors         35
7th   of 14 Floors          35
8th   of 14 Floors          34
4th   of 14 Floors          28
6th   of 14 Floors          27
3rd   of 3 Floors           26
1st   of 14 Floors          26
2nd   of 2 Floors           26
8th   of 19 Floors          24
5th   of 14 Floors          24
3rd   of 14 Floors          24
1st   of 1 Floors           23
9th   of 9 Floors           23
9th   of 14 Floors          23
5th   of 12 Floors          22
11st   of 14 Floors         22
2nd   of 3 Floors           22
2nd   of 14 Floors          21
8th   of 18 Floors          20
10th   of 19 Floors         18
6th   of 18 Floors          18
7th   of 18 Floors          17
Ground of 1 Floors          17
7th   of 15 Floors          17
12nd   of 12 Floors         17
9th   of 13 Floors          17
10th   of 18 Floors         17
5th   of 15 Floors          16
3rd   of 18 Floors          16
2nd   of 12 Floors          15
9th   of 15 Floors          15
1st   of 3 Floors           15
6th   of 12 Floors          15
6th   of 19 Floors          14
5th   of 5 Floors           13
Ground of 4 Floors          13
3rd   of 13 Floors          13
6th   of 10 Floors          13
10th   of 26 Floors         13
7th   of 7 Floors           13
1st   of 2 Floors           13
6th   of 15 Floors          12
10th   of 10 Floors         12
9th   of 26 Floors          11
4th   of 10 Floors          11
6th   of 6 Floors           11
11st   of 18 Floors         11
15th   of 19 Floors         11
9th   of 24 Floors          11
17th   of 17 Floors         11
16th   of 19 Floors         11
8th   of 8 Floors           11
8th   of 12 Floors          11
4th   of 13 Floors          11
7th   of 26 Floors          10
4th   of 12 Floors          10
7th   of 21 Floors          10
7th   of 13 Floors          10
2nd   of 19 Floors          10
12nd   of 18 Floors         10
6th   of 13 Floors          10
4th   of 15 Floors          10
1st   of 26 Floors          10
3rd   of 9 Floors           10
10th   of 12 Floors         10
3rd   of 5 Floors           10
14th   of 15 Floors          9
14th   of 19 Floors          9
12nd   of 17 Floors          9
5th   of 18 Floors           9
3rd   of 12 Floors           9
18th   of 19 Floors          9
8th   of 15 Floors           9
6th   of 16 Floors           9
15th   of 29 Floors          9
8th   of 22 Floors           9
9th   of 20 Floors           9
7th   of 17 Floors           9
13rd   of 14 Floors          9
7th   of 12 Floors           9
6th   of 26 Floors           9
12nd   of 19 Floors          8
10th   of 17 Floors          8
5th   of 9 Floors            8
3rd   of 15 Floors           8
2nd   of 8 Floors            8
9th   of 18 Floors           8
8th   of 24 Floors           8
10th   of 13 Floors          8
8th   of 26 Floors           8
1st   of 19 Floors           8
2nd   of 15 Floors           8
4th   of 26 Floors           8
12nd   of 26 Floors          8
3rd   of 19 Floors           8
12nd   of 24 Floors          8
9th   of 12 Floors           8
8th   of 13 Floors           8
14th   of 24 Floors          8
5th   of 13 Floors           8
2nd   of 5 Floors            8
11st   of 11 Floors          7
11st   of 26 Floors          7
9th   of 19 Floors           7
5th   of 29 Floors           7
11st   of 24 Floors          7
11st   of 13 Floors          7
16th   of 16 Floors          7
2nd   of 13 Floors           7
7th   of 19 Floors           7
5th   of 20 Floors           7
12nd   of 13 Floors          7
2nd   of 17 Floors           7
13rd   of 13 Floors          7
4th   of 19 Floors           7
8th   of 21 Floors           7
10th   of 21 Floors          7
8th   of 10 Floors           7
1st   of 13 Floors           7
2nd   of 10 Floors           7
12nd   of 15 Floors          7
Ground of 16 Floors          6
11st   of 12 Floors          6
1st   of 5 Floors            6
14th   of 27 Floors          6
5th   of 22 Floors           6
2nd   of 20 Floors           6
16th   of 18 Floors          6
12nd   of 22 Floors          6
1st   of 10 Floors           6
17th   of 19 Floors          6
10th   of 29 Floors          6
11st   of 19 Floors          6
5th   of 10 Floors           6
Ground of 3 Floors           6
15th   of 15 Floors          6
3rd   of 25 Floors           6
Ground of 15 Floors          6
4th   of 17 Floors           6
4th   of 18 Floors           6
10th   of 20 Floors          6
6th   of 9 Floors            6
19th   of 19 Floors          6
7th   of 20 Floors           6
5th   of 25 Floors           6
10th   of 15 Floors          6
11st   of 16 Floors          5
7th   of 8 Floors            5
4th   of 9 Floors            5
9th   of 11 Floors           5
8th   of 9 Floors            5
7th   of 27 Floors           5
15th   of 28 Floors          5
9th   of 30 Floors           5
Ground of 19 Floors          5
5th   of 8 Floors            5
12nd   of 29 Floors          5
9th   of 22 Floors           5
8th   of 30 Floors           5
6th   of 17 Floors           5
15th   of 18 Floors          5
3rd   of 20 Floors           5
18th   of 29 Floors          5
10th   of 25 Floors          5
4th   of 27 Floors           5
14th   of 29 Floors          5
5th   of 19 Floors           5
1st   of 12 Floors           5
Ground of 21 Floors          5
14th   of 16 Floors          5
11st   of 25 Floors          5
Ground of 12 Floors          5
6th   of 11 Floors           5
15th   of 21 Floors          5
12nd   of 21 Floors          5
10th   of 27 Floors          5
10th   of 24 Floors          5
4th   of 22 Floors           5
6th   of 20 Floors           5
16th   of 26 Floors          5
11st   of 30 Floors          5
1st   of 7 Floors            5
1st   of 15 Floors           5
11st   of 29 Floors          5
20th   of 26 Floors          4
13rd   of 19 Floors          4
7th   of 11 Floors           4
25th   of 25 Floors          4
8th   of 16 Floors           4
13rd   of 21 Floors          4
17th   of 25 Floors          4
3rd   of 17 Floors           4
12nd   of 30 Floors          4
5th   of 16 Floors           4
7th   of 24 Floors           4
13rd   of 25 Floors          4
17th   of 26 Floors          4
15th   of 16 Floors          4
8th   of 20 Floors           4
3rd   of 10 Floors           4
2nd   of 11 Floors           4
15th   of 26 Floors          4
3rd   of 22 Floors           4
5th   of 24 Floors           4
5th   of 23 Floors           4
Ground of 13 Floors          4
6th   of 30 Floors           4
17th   of 18 Floors          4
14th   of 26 Floors          4
15th   of 25 Floors          4
2nd   of 9 Floors            4
22nd   of 30 Floors          4
15th   of 23 Floors          4
Ground of 17 Floors          4
17th   of 24 Floors          4
15th   of 32 Floors          4
7th   of 9 Floors            4
3rd   of 11 Floors           4
20th   of 20 Floors          4
23rd   of 26 Floors          4
18th   of 32 Floors          4
14th   of 21 Floors          4
2nd   of 16 Floors           4
7th   of 10 Floors           4
19th   of 40 Floors          4
9th   of 10 Floors           4
12nd   of 16 Floors          4
14th   of 17 Floors          4
1st   of 18 Floors           4
11st   of 17 Floors          4
11st   of 15 Floors          4
14th   of 18 Floors          4
19th   of 24 Floors          4
4th   of 8 Floors            4
11st   of 20 Floors          4
22nd   of 24 Floors          4
3rd   of 26 Floors           3
3rd   of 16 Floors           3
10th   of 16 Floors          3
13rd   of 15 Floors          3
10th   of 28 Floors          3
12nd   of 23 Floors          3
4th   of 20 Floors           3
2nd   of 26 Floors           3
31st   of 32 Floors          3
1st   of 11 Floors           3
8th   of 17 Floors           3
21st   of 24 Floors          3
19th   of 21 Floors          3
17th   of 30 Floors          3
1st   of 35 Floors           3
4th   of 21 Floors           3
27th   of 27 Floors          3
14th   of 32 Floors          3
11st   of 27 Floors          3
10th   of 23 Floors          3
2nd   of 22 Floors           3
24th   of 24 Floors          3
21st   of 22 Floors          3
17th   of 20 Floors          3
4th   of 16 Floors           3
6th   of 29 Floors           3
6th   of 24 Floors           3
8th   of 25 Floors           3
30th   of 32 Floors          3
19th   of 30 Floors          3
4th   of 29 Floors           3
17th   of 29 Floors          3
18th   of 18 Floors          3
6th   of 21 Floors           3
5th   of 17 Floors           3
1st   of 25 Floors           3
5th   of 26 Floors           3
19th   of 29 Floors          3
18th   of 30 Floors          3
23rd   of 23 Floors          3
12nd   of 27 Floors          3
18th   of 26 Floors          3
8th   of 11 Floors           3
6th   of 22 Floors           3
6th   of 23 Floors           3
7th   of 23 Floors           3
15th   of 40 Floors          3
15th   of 20 Floors          3
15th   of 22 Floors          3
Ground of 18 Floors          3
16th   of 20 Floors          3
9th   of 21 Floors           3
3rd   of 8 Floors            3
6th   of 8 Floors            3
15th   of 39 Floors          3
20th   of 28 Floors          3
8th   of 40 Floors           3
Ground of 26 Floors          3
10th   of 30 Floors          3
26th   of 30 Floors          3
5th   of 30 Floors           3
9th   of 16 Floors           3
9th   of 40 Floors           3
11st   of 23 Floors          2
Lower Ground of 4 Floors     2
2nd   of 40 Floors           2
23rd   of 29 Floors          2
21st   of 27 Floors          2
13rd   of 20 Floors          2
9th   of 29 Floors           2
10th   of 40 Floors          2
25th   of 29 Floors          2
7th   of 22 Floors           2
13rd   of 30 Floors          2
4th   of 34 Floors           2
9th   of 27 Floors           2
8th   of 23 Floors           2
19th   of 27 Floors          2
3rd   of 24 Floors           2
27th   of 29 Floors          2
2nd   of 28 Floors           2
40th   of 40 Floors          2
17th   of 23 Floors          2
4th   of 7 Floors            2
15th   of 24 Floors          2
2nd   of 18 Floors           2
2nd   of 7 Floors            2
2nd   of 25 Floors           2
24th   of 30 Floors          2
2nd   of 6 Floors            2
20th   of 22 Floors          2
22nd   of 25 Floors          2
2nd   of 32 Floors           2
1st   of 30 Floors           2
43   of 47 Floors            2
1st   of 20 Floors           2
15th   of 31 Floors          2
1st   of 8 Floors            2
11st   of 21 Floors          2
23rd   of 34 Floors          2
16th   of 34 Floors          2
18th   of 24 Floors          2
16th   of 30 Floors          2
16th   of 27 Floors          2
7th   of 30 Floors           2
14th   of 20 Floors          2
19th   of 20 Floors          2
16th   of 21 Floors          2
8th   of 34 Floors           2
25th   of 30 Floors          2
16th   of 24 Floors          2
20th   of 23 Floors          2
16th   of 36 Floors          2
9th   of 28 Floors           2
2nd   of 24 Floors           2
1st   of 17 Floors           2
3rd   of 33 Floors           2
8th   of 32 Floors           2
10th   of 32 Floors          2
Ground of 51 Floors          2
39th   of 40 Floors          2
28th   of 30 Floors          2
7th   of 16 Floors           2
13rd   of 40 Floors          2
20th   of 25 Floors          2
9th   of 17 Floors           2
4th   of 5 Floors            2
12nd   of 25 Floors          2
1st   of 24 Floors           2
6th   of 31 Floors           2
7th   of 29 Floors           2
1st   of 22 Floors           2
10th   of 22 Floors          2
5th   of 11 Floors           2
2nd   of 21 Floors           2
17th   of 33 Floors          2
8th   of 28 Floors           2
10th   of 11 Floors          2
Ground of 23 Floors          2
8th   of 29 Floors           2
3rd   of 27 Floors           2
14th   of 28 Floors          2
3rd   of 32 Floors           2
15th   of 17 Floors          2
16th   of 32 Floors          2
3rd   of 29 Floors           2
18th   of 21 Floors          2
15th   of 45 Floors          2
7th   of 36 Floors           2
1st   of 16 Floors           2
4th   of 11 Floors           2
5th   of 35 Floors           1
13rd   of 34 Floors          1
3rd   of 28 Floors           1
12nd   of 40 Floors          1
7th   of 40 Floors           1
13rd   of 26 Floors          1
17th   of 28 Floors          1
18th   of 35 Floors          1
22nd   of 40 Floors          1
14th   of 25 Floors          1
Ground of 2 Floors           1
16th   of 41 Floors          1
13rd   of 22 Floors          1
3rd   of 7 Floors            1
17th   of 31 Floors          1
Ground of 40 Floors          1
Ground of 5 Floors           1
21st   of 23 Floors          1
Ground of 22 Floors          1
10th   of 33 Floors          1
3rd   of 30 Floors           1
3rd   of 31 Floors           1
Lower Ground of 1 Floors     1
19th   of 32 Floors          1
Ground of 6 Floors           1
13rd   of 17 Floors          1
20th   of 24 Floors          1
45   of 47 Floors            1
22nd   of 23 Floors          1
30th   of 34 Floors          1
Ground of 25 Floors          1
16th   of 45 Floors          1
1st   of 6 Floors            1
9th   of 25 Floors           1
13rd   of 47 Floors          1
5th   of 36 Floors           1
34th   of 34 Floors          1
34th   of 42 Floors          1
9th   of 23 Floors           1
29th   of 39 Floors          1
33rd   of 33 Floors          1
27th   of 30 Floors          1
4th   of 6 Floors            1
7th   of 28 Floors           1
8th   of 35 Floors           1
Ground of 29 Floors          1
16th   of 35 Floors          1
44   of 47 Floors            1
5th   of 6 Floors            1
22nd   of 26 Floors          1
3rd   of 36 Floors           1
29th   of 29 Floors          1
16th   of 31 Floors          1
5th   of 21 Floors           1
14th   of 41 Floors          1
5th   of 34 Floors           1
24th   of 36 Floors          1
17th   of 22 Floors          1
21st   of 36 Floors          1
23rd   of 24 Floors          1
18th   of 22 Floors          1
Basement of 13 Floors        1
12nd   of 34 Floors          1
17th   of 47 Floors          1
18th   of 20 Floors          1
24th   of 27 Floors          1
21st   of 26 Floors          1
26th   of 47 Floors          1
7th   of 25 Floors           1
Ground of 11 Floors          1
8th   of 42 Floors           1
26th   of 34 Floors          1
21st   of 29 Floors          1
14th   of 22 Floors          1
33rd   of 42 Floors          1
1st   of 44 Floors           1
24th   of 31 Floors          1
24th   of 51 Floors          1
11st   of 22 Floors          1
2nd   of 36 Floors           1
19th   of 31 Floors          1
16th   of 51 Floors          1
25th   of 36 Floors          1
21st   of 28 Floors          1
7th   of 42 Floors           1
10th   of 51 Floors          1
15th   of 30 Floors          1
Ground of 24 Floors          1
35th   of 35 Floors          1
10th   of 39 Floors          1
33rd   of 48 Floors          1
21st   of 41 Floors          1
32nd   of 32 Floors          1
32nd   of 55 Floors          1
20th   of 32 Floors          1
Basement of 28 Floors        1
19th   of 41 Floors          1
20th   of 34 Floors          1
29th   of 31 Floors          1
16th   of 22 Floors          1
18th   of 25 Floors          1
23rd   of 28 Floors          1
11st   of 36 Floors          1
28th   of 28 Floors          1
Basement of 4 Floors         1
2nd   of 34 Floors           1
4th   of 40 Floors           1
20th   of 47 Floors          1
27th   of 48 Floors          1
6th   of 7 Floors            1
3rd   of 6 Floors            1
20th   of 40 Floors          1
31st   of 40 Floors          1
9th   of 42 Floors           1
4th   of 28 Floors           1
7th   of 32 Floors           1
30th   of 40 Floors          1
4th   of 25 Floors           1
19th   of 23 Floors          1
5th   of 27 Floors           1
24th   of 39 Floors          1
20th   of 43 Floors          1
21st   of 51 Floors          1
12nd   of 28 Floors          1
10th   of 34 Floors          1
18th   of 23 Floors          1
12nd   of 32 Floors          1
23rd   of 40 Floors          1
5th   of 32 Floors           1
1st   of 9 Floors            1
20th   of 29 Floors          1
13rd   of 18 Floors          1
7th   of 34 Floors           1
16th   of 25 Floors          1
6th   of 25 Floors           1
3rd   of 40 Floors           1
12nd   of 39 Floors          1
8th   of 31 Floors           1
20th   of 30 Floors          1
18th   of 51 Floors          1
19th   of 22 Floors          1
19th   of 26 Floors          1
2nd   of 27 Floors           1
14th   of 51 Floors          1
19th   of 39 Floors          1
38th   of 40 Floors          1
15th   of 27 Floors          1
18th   of 40 Floors          1
35th   of 51 Floors          1
22nd   of 28 Floors          1
17th   of 21 Floors          1
4th   of 39 Floors           1
24th   of 32 Floors          1
8th   of 27 Floors           1
28th   of 29 Floors          1
23rd   of 36 Floors          1
Name: count, dtype: int64

In [146]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement' , '-1').str.replace('Lower' , '0').str.extract(r'(\d+)')

In [147]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [148]:
df['facing'].value_counts()

facing
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [149]:
df['facing'].fillna('NA',inplace=True)

C:\Users\virat\AppData\Local\Temp\ipykernel_7972\3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)

In [150]:
df['facing'].value_counts()

facing
NA            874
North-East    505
East          489
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [151]:
df.insert(loc = 4 , column = 'area' ,value = round((df['price']*10000000)/df['price_per_sqft']))

In [152]:
df.insert(loc = 1 , column = 'property_type' , value = 'flat')

In [153]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NA,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NA,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NA,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [154]:
df.shape

(2996, 20)

In [ ]:
df.to_csv('flats')